# Bengali (India) translations for glance.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-01-31 06:01+0000\n"
"PO-Revision-Date: 2013-10-28 06:02+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Bengali (India) "
"(http://www.transifex.com/projects/p/openstack/language/bn_IN/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/notifier.py:31
msgid ""
"Notifications can be sent when images are create, updated or deleted. "
"There are three methods of sending notifications, logging (via the "
"log_file directive), rabbit (via a rabbitmq queue), qpid (via a Qpid "
"message queue), or noop (no notifications sent, the default). "
"(DEPRECATED)"
msgstr ""

#: glance/notifier.py:62
msgid "notifier_strategy was deprecated in favor of `notification_driver`"
msgstr ""

#: glance/notifier.py:212 glance/api/common.py:82
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr ""

#: glance/notifier.py:222 glance/api/v1/upload_utils.py:184
#: glance/api/v2/image_data.py:90
#, python-format
msgid "Image storage media is full: %s"
msgstr ""

#: glance/notifier.py:226 glance/api/v1/upload_utils.py:193
#: glance/api/v2/image_data.py:108
#, python-format
msgid "Insufficient permissions on image storage media: %s"
msgstr ""

#: glance/notifier.py:231
#, python-format
msgid "Cannot save data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:237
#, python-format
msgid "Unable to upload duplicate image data for image%(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:244
#, python-format
msgid "Not allowed to upload image data for image %(image_id)s: %(error)s"
msgstr ""

#: glance/notifier.py:250
#, python-format
msgid ""
"Image %(image_id)s could not be found after upload. The image may have "
"been deleted during the upload: %(error)s"
msgstr ""

#: glance/notifier.py:257
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to HTTP error: "
"%(error)s"
msgstr ""

#: glance/notifier.py:264
#, python-format
msgid ""
"Failed to upload image data for image %(image_id)s due to internal error:"
" %(error)s"
msgstr ""

#: glance/schema.py:56
#, python-format
msgid "custom properties (%(props)s) conflict with base properties"
msgstr ""

#: glance/api/authorization.py:109 glance/api/authorization.py:120
#, python-format
msgid "You cannot get image member for %s"
msgstr ""

#: glance/api/authorization.py:128
#, python-format
msgid "You cannot delete image member for %s"
msgstr ""

#: glance/api/authorization.py:137
#, python-format
msgid "You cannot add image member for %s"
msgstr ""

#: glance/api/authorization.py:146
#, python-format
msgid "You cannot update image member %s"
msgstr ""

#: glance/api/authorization.py:165
#, python-format
msgid "You are not permitted to create images owned by '%s'."
msgstr ""

#: glance/api/authorization.py:183
msgid "You are not permitted to create image members for the image."
msgstr ""

#: glance/api/authorization.py:188 glance/api/authorization.py:360
msgid "Public images do not have members."
msgstr ""

#: glance/api/authorization.py:204
#, python-format
msgid "You are not permitted to modify '%(attr)s' on this %(resource)s."
msgstr ""

#: glance/api/authorization.py:214
msgid "You are not permitted to modify locations for this image."
msgstr ""

#: glance/api/authorization.py:235
#, python-format
msgid "You are not permitted to modify '%s' on this image."
msgstr ""

#: glance/api/authorization.py:239
msgid "You are not permitted to modify this image."
msgstr ""

#: glance/api/authorization.py:252
msgid "You are not permitted to modify tags on this image."
msgstr ""

#: glance/api/authorization.py:292
msgid "You are not permitted to delete this image."
msgstr ""

#: glance/api/authorization.py:303
msgid "You are not permitted to upload data for this image."
msgstr ""

#: glance/api/authorization.py:339 glance/api/authorization.py:343
#: glance/api/authorization.py:347
msgid "You are not permitted to set status on this task."
msgstr ""

#: glance/api/authorization.py:394
#, python-format
msgid "You are not permitted to create this task with owner as: %s"
msgstr ""

#: glance/api/common.py:44
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""

#: glance/api/common.py:51
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""

#: glance/api/common.py:56
#, python-format
msgid "Corrupt image download for image %(image_id)s"
msgstr ""

#: glance/api/policy.py:33
msgid "The location of the policy file."
msgstr ""

#: glance/api/policy.py:35
msgid "The default policy to use."
msgstr ""

#: glance/api/policy.py:82
#, python-format
msgid "Loaded %(rule_type)spolicy rules: %(text_rules)s"
msgstr ""

#: glance/api/policy.py:95
msgid "Unable to find policy file"
msgstr ""

#: glance/api/policy.py:105
#, python-format
msgid "Loading policy from %s"
msgstr ""

#: glance/api/policy.py:219 glance/quota/__init__.py:334
#: glance/store/__init__.py:634
#, python-format
msgid "Invalid locations: %s"
msgstr ""

#: glance/api/middleware/cache.py:57
msgid "Initialized image cache middleware"
msgstr ""

#: glance/api/middleware/cache.py:125
#, python-format
msgid "Cache hit for image '%s'"
msgstr ""

#: glance/api/middleware/cache.py:132
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did"
" not contain metadata for that image!"
msgstr ""

#: glance/api/middleware/cache.py:230
#, python-format
msgid "could not find %s"
msgstr ""

#: glance/api/middleware/cache.py:238
#, python-format
msgid "Removing image %s from cache"
msgstr ""

#: glance/api/middleware/cache.py:250
msgid "Checksum header is missing."
msgstr ""

#: glance/api/middleware/cache_manage.py:72
msgid "Initialized image cache management middleware"
msgstr ""

#: glance/api/middleware/context.py:28
msgid ""
"When true, this option sets the owner of an image to be the tenant. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: glance/api/middleware/context.py:33
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: glance/api/middleware/context.py:36
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: glance/api/middleware/context.py:52
msgid "Unable to retrieve request id from context"
msgstr ""

#: glance/api/middleware/context.py:109
msgid "Invalid service catalog json."
msgstr ""

#: glance/api/middleware/gzip.py:33
msgid "Initialized gzip middleware"
msgstr ""

#: glance/api/middleware/version_negotiation.py:41
#, python-format
msgid "Determining version of request: %(method)s %(path)s Accept: %(accept)s"
msgstr ""

#: glance/api/middleware/version_negotiation.py:53
msgid "Using media-type versioning"
msgstr ""

#: glance/api/middleware/version_negotiation.py:57
msgid "Using url versioning"
msgstr ""

#: glance/api/middleware/version_negotiation.py:64
msgid "Unknown version. Returning version choices."
msgstr ""

#: glance/api/middleware/version_negotiation.py:69
#, python-format
msgid "Matched version: v%d"
msgstr ""

#: glance/api/v1/controller.py:41 glance/api/v1/members.py:75
#, python-format
msgid "Image with identifier %s not found"
msgstr ""

#: glance/api/v1/controller.py:46
msgid "Forbidden image access"
msgstr ""

#: glance/api/v1/controller.py:59
#, python-format
msgid "Image %s is not active"
msgstr ""

#: glance/api/v1/controller.py:81
#, python-format
msgid "Store for image_id not found: %s"
msgstr ""

#: glance/api/v1/images.py:82
#, python-format
msgid "Image name too long: %d"
msgstr ""

#: glance/api/v1/images.py:93
msgid ""
"Invalid mix of disk and container formats. When setting a disk or "
"container format to one of 'aki', 'ari', or 'ami', the container and disk"
" formats must match."
msgstr ""

#: glance/api/v1/images.py:171
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(num)s, Maximum: %(quota)s"
msgstr ""

#: glance/api/v1/images.py:193 glance/api/v1/images.py:237
#: glance/api/v1/images.py:271
#, python-format
msgid "Property '%s' is protected"
msgstr ""

#: glance/api/v1/images.py:418
#, python-format
msgid "External sourcing not supported for store %s"
msgstr ""

#: glance/api/v1/images.py:491
#, python-format
msgid "Required store %s is invalid"
msgstr ""

#: glance/api/v1/images.py:503 glance/api/v1/images.py:875
#, python-format
msgid "Invalid location %s"
msgstr ""

#: glance/api/v1/images.py:526
#, python-format
msgid "An image with identifier %s already exists"
msgstr ""

#: glance/api/v1/images.py:533
#, python-format
msgid "Failed to reserve image. Got error: %(e)s"
msgstr ""

#: glance/api/v1/images.py:540
msgid "Forbidden to reserve image."
msgstr ""

#: glance/api/v1/images.py:567
#, python-format
msgid "Copy from external source failed: %s"
msgstr ""

#: glance/api/v1/images.py:576
msgid "Content-Type must be application/octet-stream"
msgstr ""

#: glance/api/v1/images.py:587
#, python-format
msgid "Setting image %s to status 'saving'"
msgstr ""

#: glance/api/v1/images.py:591
#, python-format
msgid "Uploading image data for image %(image_id)s to %(scheme)s store"
msgstr ""

#: glance/api/v1/images.py:642
#, python-format
msgid "Failed to activate image. Got error: %(e)s"
msgstr ""

#: glance/api/v1/images.py:681
msgid "It's invalid to provide multiple image sources."
msgstr ""

#: glance/api/v1/images.py:692
msgid "Triggering asynchronous copy from external source"
msgstr ""

#: glance/api/v1/images.py:707
#, python-format
msgid ""
"Provided image size must match the stored image size. (provided size: "
"%(ps)d, stored size: %(ss)d)"
msgstr ""

#: glance/api/v1/images.py:829
msgid "Forbidden to update deleted image."
msgstr ""

#: glance/api/v1/images.py:840
#, python-format
msgid "Forbidden to modify '%s' of active image."
msgstr ""

#: glance/api/v1/images.py:858
msgid "Cannot upload to an unqueued image"
msgstr ""

#: glance/api/v1/images.py:882
msgid "Attempted to update Location field for an image not in queued status."
msgstr ""

#: glance/api/v1/images.py:922 glance/registry/api/v1/images.py:449
#, python-format
msgid "Failed to update image metadata. Got error: %(e)s"
msgstr ""

#: glance/api/v1/images.py:929
#, python-format
msgid "Failed to find image to update: %(e)s"
msgstr ""

#: glance/api/v1/images.py:936
#, python-format
msgid "Forbidden to update image: %(e)s"
msgstr ""

#: glance/api/v1/images.py:975
msgid "Image is protected"
msgstr ""

#: glance/api/v1/images.py:982
#, python-format
msgid "Forbidden to delete a %s image."
msgstr ""

#: glance/api/v1/images.py:987
#, python-format
msgid "Image %s not found."
msgstr ""

#: glance/api/v1/images.py:1013 glance/store/scrubber.py:176
#, python-format
msgid "Failed to find image to delete: %(e)s"
msgstr ""

#: glance/api/v1/images.py:1020
#, python-format
msgid "Forbidden to delete image: %(e)s"
msgstr ""

#: glance/api/v1/images.py:1043 glance/store/__init__.py:214
#, python-format
msgid "Store for scheme %s not found"
msgstr ""

#: glance/api/v1/images.py:1082 glance/api/v1/upload_utils.py:202
#, python-format
msgid "Denying attempt to upload image larger than %d bytes."
msgstr ""

#: glance/api/v1/members.py:40 glance/registry/api/v1/members.py:32
msgid "No authenticated user"
msgstr ""

#: glance/api/v1/members.py:52
#, python-format
msgid "Image with identifier %s has been deleted."
msgstr ""

#: glance/api/v1/members.py:79
msgid "Unauthorized image access"
msgstr ""

#: glance/api/v1/members.py:118 glance/common/exception.py:283
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image members for "
"this image. Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/api/v1/upload_utils.py:72
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr ""

#: glance/api/v1/upload_utils.py:107
#, python-format
msgid "Cleaning up %s after exceeding the quota"
msgstr ""

#: glance/api/v1/upload_utils.py:115
#, python-format
msgid ""
"Supplied %(attr)s (%(supplied)s) and %(attr)s generated from uploaded "
"image (%(actual)s) did not match. Setting image status to 'killed'."
msgstr ""

#: glance/api/v1/upload_utils.py:135
#, python-format
msgid ""
"Updating image %(image_id)s data. Checksum set to %(checksum)s, size set "
"to %(size)d"
msgstr ""

#: glance/api/v1/upload_utils.py:148
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted"
" during the upload."
msgstr ""

#: glance/api/v1/upload_utils.py:164
#, python-format
msgid "Attempt to upload duplicate image: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid "Forbidden upload attempt: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:212 glance/api/v2/images.py:135
#, python-format
msgid "Denying attempt to upload image because it exceeds the .quota: %s"
msgstr ""

#: glance/api/v1/upload_utils.py:226
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr ""

#: glance/api/v1/upload_utils.py:233
msgid "Client disconnected before sending all data to backend"
msgstr ""

#: glance/api/v1/upload_utils.py:241
#, python-format
msgid "Failed to upload image %s"
msgstr ""

#: glance/api/v2/image_data.py:55
#, python-format
msgid ""
"Image %(id)s could not be found after upload.The image may have been "
"deleted during the upload: %(error)s Cleaning up the chunks uploaded"
msgstr ""

#: glance/api/v2/image_data.py:81
#, python-format
msgid "Not allowed to upload image data for image %s"
msgstr ""

#: glance/api/v2/image_data.py:96
#, python-format
msgid "Image exceeds the storage quota: %s"
msgstr ""

#: glance/api/v2/image_data.py:102
#, python-format
msgid "The incoming image is too large: %s"
msgstr ""

#: glance/api/v2/image_data.py:114
msgid "Failed to upload image data due to HTTP error"
msgstr ""

#: glance/api/v2/image_data.py:118
msgid "Failed to upload image data due to internal error"
msgstr ""

#: glance/api/v2/image_members.py:189 glance/api/v2/images.py:290
msgid "Body expected in request."
msgstr ""

#: glance/api/v2/image_members.py:200
msgid "Member to be added not specified"
msgstr ""

#: glance/api/v2/image_members.py:203
msgid "Member can't be empty"
msgstr ""

#: glance/api/v2/image_members.py:212
msgid "Status not specified"
msgstr ""

#: glance/api/v2/image_members.py:267
msgid "An identifier for the image member (tenantId)"
msgstr ""

#: glance/api/v2/image_members.py:271 glance/api/v2/images.py:643
msgid "An identifier for the image"
msgstr ""

#: glance/api/v2/image_members.py:277
msgid "Date and time of image member creation"
msgstr ""

#: glance/api/v2/image_members.py:284
msgid "Date and time of last modification of image member"
msgstr ""

#: glance/api/v2/image_members.py:289
msgid "The status of this image member"
msgstr ""

#: glance/api/v2/images.py:126
#, python-format
msgid "Failed to find image %(image_id)s to update"
msgstr ""

#: glance/api/v2/images.py:159 glance/api/v2/images.py:187
#, python-format
msgid "Property %s does not exist."
msgstr ""

#: glance/api/v2/images.py:171
#, python-format
msgid "Property %s already present."
msgstr ""

#: glance/api/v2/images.py:182
#, python-format
msgid "Property %s may not be removed."
msgstr ""

#: glance/api/v2/images.py:220
msgid "Cannot replace locations from a non-empty list to a non-empty list."
msgstr ""

#: glance/api/v2/images.py:243
msgid "Invalid position for adding a location."
msgstr ""

#: glance/api/v2/images.py:258
msgid "Invalid position for removing a location."
msgstr ""

#: glance/api/v2/images.py:322 glance/api/v2/images.py:344
#, python-format
msgid "Unable to find '%s' in JSON Schema change"
msgstr ""

#: glance/api/v2/images.py:330
msgid ""
"Operation objects must contain only one member named \"add\", \"remove\","
" or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:335
msgid ""
"Operation objects must contain exactly one member named \"add\", "
"\"remove\", or \"replace\"."
msgstr ""

#: glance/api/v2/images.py:372
#, python-format
msgid "Pointer `%s` does not start with \"/\"."
msgstr ""

#: glance/api/v2/images.py:375
#, python-format
msgid "Pointer `%s` contains adjacent \"/\"."
msgstr ""

#: glance/api/v2/images.py:378
#, python-format
msgid "Pointer `%s` end with \"/\"."
msgstr ""

#: glance/api/v2/images.py:381
#, python-format
msgid "Pointer `%s` does not contains valid token."
msgstr ""

#: glance/api/v2/images.py:384
#, python-format
msgid "Pointer `%s` contains \"~\" not part of a recognized escape sequence."
msgstr ""

#: glance/api/v2/images.py:390
#, python-format
msgid "Operation \"%s\" requires a member named \"value\"."
msgstr ""

#: glance/api/v2/images.py:430
#, python-format
msgid "Invalid JSON pointer for this resource: '/%s'"
msgstr ""

#: glance/api/v2/images.py:442
msgid "Unrecognized JSON Schema draft version"
msgstr ""

#: glance/api/v2/images.py:463
msgid "Request body must be a JSON array of operation objects."
msgstr ""

#: glance/api/v2/images.py:468
msgid "Operations must be JSON objects."
msgstr ""

#: glance/api/v2/images.py:490 glance/api/v2/tasks.py:157
#: glance/registry/api/v1/images.py:243
msgid "limit param must be an integer"
msgstr ""

#: glance/api/v2/images.py:494 glance/api/v2/tasks.py:161
#: glance/registry/api/v1/images.py:246
msgid "limit param must be positive"
msgstr ""

#: glance/api/v2/images.py:501 glance/api/v2/tasks.py:127
#, python-format
msgid "Invalid sort direction: %s"
msgstr ""

#: glance/api/v2/images.py:508
#, python-format
msgid "Invalid status: %s"
msgstr ""

#: glance/api/v2/images.py:517
#, python-format
msgid "Invalid visibility value: %s"
msgstr ""

#: glance/api/v2/images.py:649
msgid "Descriptive name for the image"
msgstr ""

#: glance/api/v2/images.py:654
msgid "Status of the image (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:660
msgid "Scope of image accessibility"
msgstr ""

#: glance/api/v2/images.py:665
msgid "If true, image will not be deletable."
msgstr ""

#: glance/api/v2/images.py:669
msgid "md5 hash of image contents. (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:675
msgid "Size of image file in bytes (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:679
msgid "Format of the container"
msgstr ""

#: glance/api/v2/images.py:685
msgid "Format of the disk"
msgstr ""

#: glance/api/v2/images.py:691
msgid "Date and time of image registration (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:699
msgid "Date and time of the last image modification (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:705
msgid "List of strings related to the image"
msgstr ""

#: glance/api/v2/images.py:713
msgid "URL to access the image file kept in external store (READ-ONLY)"
msgstr ""

#: glance/api/v2/images.py:718
msgid "Amount of ram (in MB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:722
msgid "Amount of disk space (in GB) required to boot image."
msgstr ""

#: glance/api/v2/images.py:752
msgid "A set of URLs to access the image file kept in external store"
msgstr ""

#: glance/api/v2/images.py:791
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""

#: glance/api/v2/tasks.py:65
#, python-format
msgid "Forbidden to create task. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:103
#, python-format
msgid "Failed to find task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:108
#, python-format
msgid "Forbidden to get task %(task_id)s. Reason: %(reason)s"
msgstr ""

#: glance/api/v2/tasks.py:121
msgid "Body expected in request"
msgstr ""

#: glance/api/v2/tasks.py:136
#, python-format
msgid "Invalid status value: %s"
msgstr ""

#: glance/api/v2/tasks.py:142
#, python-format
msgid "Invalid type value: %s"
msgstr ""

#: glance/api/v2/tasks.py:149 glance/registry/api/v1/images.py:255
msgid "Invalid marker format"
msgstr ""

#: glance/api/v2/tasks.py:170
#, python-format
msgid "Task '%s' is required"
msgstr ""

#: glance/api/v2/tasks.py:180
#, python-format
msgid "Input does not contain '%s' field"
msgstr ""

#: glance/api/v2/tasks.py:276
msgid "An identifier for the task"
msgstr ""

#: glance/api/v2/tasks.py:277
msgid ""
"^([0-9a-fA-F]){8}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0-9a-fA-F]){4}-([0"
"-9a-fA-F]){12}$"
msgstr ""

#: glance/api/v2/tasks.py:282
msgid "The type of task represented by this content"
msgstr ""

#: glance/api/v2/tasks.py:289
msgid "The current status of this task"
msgstr ""

#: glance/api/v2/tasks.py:299
msgid "The parameters required by task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:303
msgid "The result of current task, JSON blob"
msgstr ""

#: glance/api/v2/tasks.py:307
msgid "An identifier for the owner of this task"
msgstr ""

#: glance/api/v2/tasks.py:311
msgid ""
"Human-readable informative message only included when appropriate "
"(usually on failure)"
msgstr ""

#: glance/api/v2/tasks.py:316
msgid "Datetime when this resource would be subject to removal"
msgstr ""

#: glance/api/v2/tasks.py:321
msgid "Datetime when this resource was created"
msgstr ""

#: glance/api/v2/tasks.py:325
msgid "Datetime when this resource was updated"
msgstr ""

#: glance/cmd/replicator.py:54
#, python-format
msgid ""
"The image %s is already present on the slave, but our check for it did "
"not find it. This indicates that we do not have permissions to see all "
"the images on the slave server."
msgstr ""

#: glance/cmd/replicator.py:104
#, python-format
msgid ""
"Request: %(method)s http://%(server)s:%(port)s%(url)s with headers "
"%(headers)s"
msgstr ""

#: glance/cmd/replicator.py:117
#, python-format
msgid "Response: %(code)s %(status)s %(headers)s"
msgstr ""

#: glance/cmd/replicator.py:239 glance/cmd/replicator.py:258
msgid "Image post done"
msgstr ""

#: glance/cmd/replicator.py:281 glance/cmd/replicator.py:318
#: glance/cmd/replicator.py:403 glance/cmd/replicator.py:482
#: glance/cmd/replicator.py:559
msgid "Too few arguments."
msgstr ""

#: glance/cmd/replicator.py:286 glance/cmd/replicator.py:324
#: glance/cmd/replicator.py:409 glance/cmd/replicator.py:489
#: glance/cmd/replicator.py:566
msgid "Bad format of the given arguments."
msgstr ""

#: glance/cmd/replicator.py:297
#, python-format
msgid "Considering image: %(image)s"
msgstr ""

#: glance/cmd/replicator.py:302
#, python-format
msgid "Total size is %(size)d bytes across %(img_count)d images"
msgstr ""

#: glance/cmd/replicator.py:332 glance/cmd/replicator.py:422
#, python-format
msgid "Considering: %s"
msgstr ""

#: glance/cmd/replicator.py:336
msgid "... storing"
msgstr ""

#: glance/cmd/replicator.py:347
msgid "... image is active"
msgstr ""

#: glance/cmd/replicator.py:367
#, python-format
msgid "metadata diff -- master has extra keys: %(keys)s"
msgstr ""

#: glance/cmd/replicator.py:373
#, python-format
msgid ""
"metadata diff -- value differs for key %(key)s: master "
"\"%(master_value)s\" vs slave \"%(slave_value)s\""
msgstr ""

#: glance/cmd/replicator.py:431
#, python-format
msgid "Stripping %(header)s from saved metadata"
msgstr ""

#: glance/cmd/replicator.py:439
#, python-format
msgid "Image %s already present"
msgstr ""

#: glance/cmd/replicator.py:443 glance/cmd/replicator.py:523
#: glance/cmd/replicator.py:589
#, python-format
msgid "Stripping %(header)s from slave metadata"
msgstr ""

#: glance/cmd/replicator.py:448 glance/cmd/replicator.py:528
msgid "... metadata has changed"
msgstr ""

#: glance/cmd/replicator.py:455
msgid "... dump is missing image data, skipping"
msgstr ""

#: glance/cmd/replicator.py:504
#, python-format
msgid "Considering %(id)s"
msgstr ""

#: glance/cmd/replicator.py:507 glance/cmd/replicator.py:519
#: glance/cmd/replicator.py:585
#, python-format
msgid "Stripping %(header)s from master metadata"
msgstr ""

#: glance/cmd/replicator.py:534
#, python-format
msgid "%s is being synced"
msgstr ""

#: glance/cmd/replicator.py:595
#, python-format
msgid ""
"%(image_id)s: field %(key)s differs (source is %(master_value)s, "
"destination is %(slave_value)s)"
msgstr ""

#: glance/cmd/replicator.py:605
#, python-format
msgid "%(image_id)s is identical"
msgstr ""

#: glance/cmd/replicator.py:609
#, python-format
msgid "%s: entirely missing from the destination"
msgstr ""

#: glance/cmd/replicator.py:716
#, python-format
msgid "Unknown command: %s"
msgstr ""

#: glance/common/auth.py:186 glance/common/auth.py:226
#, python-format
msgid "Unexpected response: %s"
msgstr ""

#: glance/common/auth.py:254
#, python-format
msgid "Unknown auth strategy '%s'"
msgstr ""

#: glance/common/auth.py:275
#, python-format
msgid "Encountered service with no \"type\": %s"
msgstr ""

#: glance/common/client.py:237
msgid ""
"You have selected to use SSL in connecting, and you have supplied a cert,"
" however you have failed to supply either a key_file parameter or set the"
" GLANCE_CLIENT_KEY_FILE environ variable"
msgstr ""

#: glance/common/client.py:245
msgid ""
"You have selected to use SSL in connecting, and you have supplied a key, "
"however you have failed to supply either a cert_file parameter or set the"
" GLANCE_CLIENT_CERT_FILE environ variable"
msgstr ""

#: glance/common/client.py:254
#, python-format
msgid "The key file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:261
#, python-format
msgid "The cert file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:268
#, python-format
msgid "The CA file you specified %s does not exist"
msgstr ""

#: glance/common/client.py:306
#, python-format
msgid "Configuring from URL: %s"
msgstr ""

#: glance/common/client.py:318
#, python-format
msgid "Appending doc_root %(doc_root)s to URL %(url)s"
msgstr ""

#: glance/common/client.py:407
#, python-format
msgid "Constructed URL: %s"
msgstr ""

#: glance/common/config.py:34
msgid ""
"Partial name of a pipeline in your paste configuration file with the "
"service name removed. For example, if your paste section name is "
"[pipeline:glance-api-keystone] use the value \"keystone\""
msgstr ""

#: glance/common/config.py:40
msgid "Name of the paste configuration file."
msgstr ""

#: glance/common/config.py:45
msgid "Supported values for the 'container_format' image attribute"
msgstr ""

#: glance/common/config.py:52
msgid "Supported values for the 'disk_format' image attribute"
msgstr ""

#: glance/common/config.py:60
msgid "Time in hours for which a task lives after, either succeeding or failing"
msgstr ""

#: glance/common/config.py:67
msgid ""
"Whether to allow users to specify image properties beyond what the image "
"schema provides"
msgstr ""

#: glance/common/config.py:70
msgid ""
"Maximum number of image members per image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:73
msgid ""
"Maximum number of properties allowed on an image. Negative values "
"evaluate to unlimited."
msgstr ""

#: glance/common/config.py:76
msgid ""
"Maximum number of tags allowed on an image. Negative values evaluate to "
"unlimited."
msgstr ""

#: glance/common/config.py:79
msgid ""
"Maximum number of locations allowed on an image. Negative values evaluate"
" to unlimited."
msgstr ""

#: glance/common/config.py:82
msgid "Python module path of data access API"
msgstr ""

#: glance/common/config.py:84
msgid ""
"Default value for the number of items returned by a request if not "
"specified explicitly in the request"
msgstr ""

#: glance/common/config.py:87
msgid "Maximum permissible number of items that could be returned by a request"
msgstr ""

#: glance/common/config.py:90
msgid ""
"Whether to include the backend image storage location in image "
"properties. Revealing storage location can be a security risk, so use "
"this setting with caution!"
msgstr ""

#: glance/common/config.py:95
msgid ""
"Whether to include the backend image locations in image properties. "
"Revealing storage location can be a security risk, so use this setting "
"with caution!  The overrides show_image_direct_url."
msgstr ""

#: glance/common/config.py:100
msgid ""
"Maximum size of image a user can upload in bytes. Defaults to "
"1099511627776 bytes (1 TB)."
msgstr ""

#: glance/common/config.py:103
msgid ""
"Set a system wide quota for every user.  This value is the total number "
"of bytes that a user can use across all storage systems.  A value of 0 "
"means unlimited."
msgstr ""

#: glance/common/config.py:107
msgid "Deploy the v1 OpenStack Images API."
msgstr ""

#: glance/common/config.py:109
msgid "Deploy the v2 OpenStack Images API."
msgstr ""

#: glance/common/config.py:111
msgid "The hostname/IP of the pydev process listening for debug connections"
msgstr ""

#: glance/common/config.py:114
msgid "The port on which a pydev process is listening for connections."
msgstr ""

#: glance/common/config.py:117
msgid ""
"Key used for encrypting sensitive metadata while talking to the registry "
"or database."
msgstr ""

#: glance/common/config.py:203
#, python-format
msgid "Loading %(app_name)s from %(conf_file)s"
msgstr ""

#: glance/common/config.py:214
#, python-format
msgid ""
"Unable to load %(app_name)s from configuration file %(conf_file)s.\n"
"Got: %(e)r"
msgstr ""

#: glance/common/exception.py:37
msgid "An unknown exception occurred"
msgstr ""

#: glance/common/exception.py:55
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: glance/common/exception.py:59
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: glance/common/exception.py:64
msgid "An object with the specified identifier was not found."
msgstr ""

#: glance/common/exception.py:68
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: glance/common/exception.py:72
msgid "The Store URI was malformed."
msgstr ""

#: glance/common/exception.py:76
msgid "An object with the same identifier already exists."
msgstr ""

#: glance/common/exception.py:80
msgid "An object with the same identifier is currently being operated on."
msgstr ""

#: glance/common/exception.py:85
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: glance/common/exception.py:89
#, python-format
msgid ""
"The size of the data %(image_size)s will exceed the limit. %(remaining)s "
"bytes remaining."
msgstr ""

#: glance/common/exception.py:94
msgid "Permission to write image storage media denied."
msgstr ""

#: glance/common/exception.py:98
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: glance/common/exception.py:102
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: glance/common/exception.py:106
msgid "Authorization failed."
msgstr ""

#: glance/common/exception.py:110
msgid "You are not authenticated."
msgstr ""

#: glance/common/exception.py:114 glance/common/exception.py:118
msgid "You are not authorized to complete this action."
msgstr ""

#: glance/common/exception.py:122
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: glance/common/exception.py:126
msgid "Data supplied was not valid."
msgstr ""

#: glance/common/exception.py:130
#: glance/openstack/common/db/sqlalchemy/utils.py:60
msgid "Sort key supplied was not valid."
msgstr ""

#: glance/common/exception.py:134
msgid "Invalid configuration in property protection file."
msgstr ""

#: glance/common/exception.py:138
msgid "Unable to filter using the specified range."
msgstr ""

#: glance/common/exception.py:142
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: glance/common/exception.py:146
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: glance/common/exception.py:150
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: glance/common/exception.py:154
msgid "There was an error migrating the database."
msgstr ""

#: glance/common/exception.py:158
msgid "There was an error connecting to a server"
msgstr ""

#: glance/common/exception.py:162
msgid "There was an error configuring the client."
msgstr ""

#: glance/common/exception.py:166
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:172
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:183
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: glance/common/exception.py:194
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: glance/common/exception.py:198
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: glance/common/exception.py:203
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: glance/common/exception.py:207
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:212
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: glance/common/exception.py:217
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: glance/common/exception.py:222
msgid "Deleting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:226
msgid "Getting images from this store is not supported."
msgstr ""

#: glance/common/exception.py:230
msgid "Adding images to this store is not supported."
msgstr ""

#: glance/common/exception.py:234
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: glance/common/exception.py:239
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: glance/common/exception.py:243
msgid "Received invalid HTTP redirect."
msgstr ""

#: glance/common/exception.py:247
msgid "Response from Keystone does not contain a Glance endpoint."
msgstr ""

#: glance/common/exception.py:251
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: glance/common/exception.py:257
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: glance/common/exception.py:261
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: glance/common/exception.py:265
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: glance/common/exception.py:270
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: glance/common/exception.py:274
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Glance."
msgstr ""

#: glance/common/exception.py:279
msgid "The provided image is too large."
msgstr ""

#: glance/common/exception.py:289
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image properties. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:294
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image tags. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:299
#, python-format
msgid ""
"The limit has been exceeded on the number of allowed image locations. "
"Attempted: %(attempted)s, Maximum: %(maximum)s"
msgstr ""

#: glance/common/exception.py:304
#, python-format
msgid "%(cls)s exception was raised in the last rpc call: %(val)s"
msgstr ""

#: glance/common/exception.py:308
msgid "An unknown task exception occurred"
msgstr ""

#: glance/common/exception.py:312
#, python-format
msgid "Task with the given id %(task_id)s was not found"
msgstr ""

#: glance/common/exception.py:316
#, python-format
msgid "Provided status of task is unsupported: %(status)s"
msgstr ""

#: glance/common/exception.py:320
#, python-format
msgid "Provided type of task is unsupported: %(type)s"
msgstr ""

#: glance/common/exception.py:324
#, python-format
msgid "Status transition from %(cur_status)s to %(new_status)s is not allowed"
msgstr ""

#: glance/common/exception.py:329
#, python-format
msgid "The location %(location)s already exists"
msgstr ""

#: glance/common/exception.py:333 glance/store/__init__.py:702
msgid "No image data could be found"
msgstr ""

#: glance/common/exception.py:337
#, python-format
msgid "Invalid value '%(value)s' for parameter '%(param)s': %(extra_msg)s"
msgstr ""

#: glance/common/exception.py:342
#, python-format
msgid ""
"Image status transition from %(cur_status)s to %(new_status)s is not "
"allowed"
msgstr ""

#: glance/common/property_utils.py:37
msgid "The location of the property protection file."
msgstr ""

#: glance/common/property_utils.py:40
msgid ""
"This config value indicates whether \"roles\" or \"policies\" are used in"
" the property protection file."
msgstr ""

#: glance/common/property_utils.py:75
#, python-format
msgid "Couldn't find property protection file %(file)s: %(error)s."
msgstr ""

#: glance/common/property_utils.py:82
#, python-format
msgid ""
"Invalid value '%s' for 'property_protection_rule_format'. The permitted "
"values are 'roles' and 'policies'"
msgstr ""

#: glance/common/property_utils.py:101
#, python-format
msgid ""
"Multiple policies '%s' not allowedfor a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/property_utils.py:114
#, python-format
msgid ""
"Malformed property protection rule in [%(prop)s] %(op)s=%(perm)s: '@' and"
" '!' are mutually exclusive"
msgstr ""

#: glance/common/property_utils.py:127
#, python-format
msgid ""
"Property protection on operation %(operation)s for rule %(rule)s is not "
"found. No role will be allowed to perform this operation."
msgstr ""

#: glance/common/property_utils.py:139
#, python-format
msgid "Encountered a malformed property protection rule %(rule)s: %(error)s."
msgstr ""

#: glance/common/rpc.py:138
msgid "Request must be a list of commands"
msgstr ""

#: glance/common/rpc.py:143
#, python-format
msgid "Bad Command: %s"
msgstr ""

#: glance/common/rpc.py:150
#, python-format
msgid "Wrong command structure: %s"
msgstr ""

#: glance/common/rpc.py:159
msgid "Command not found"
msgstr ""

#: glance/common/rpc.py:181
#, python-format
msgid ""
"RPC Call Error: %(val)s\n"
"%(tb)s"
msgstr ""

#: glance/common/utils.py:103
#, python-format
msgid "Error: cooperative_iter exception %s"
msgstr ""

#: glance/common/utils.py:251
#, python-format
msgid "Bad header: %(header_name)s"
msgstr ""

#: glance/common/utils.py:261
#, python-format
msgid "Cannot convert image %(key)s '%(value)s' to an integer."
msgstr ""

#: glance/common/utils.py:268
#, python-format
msgid "Image %(key)s must be >= 0 ('%(value)s' specified)."
msgstr ""

#: glance/common/utils.py:431
msgid "Read-only access"
msgstr ""

#: glance/common/utils.py:477
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: glance/common/utils.py:508
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it.  Error: %(ioe)s"
msgstr ""

#: glance/common/utils.py:515
#, python-format
msgid ""
"There is a problem with your %(error_key_name)s %(error_filename)s.  "
"Please verify it. OpenSSL error: %(ce)s"
msgstr ""

#: glance/common/utils.py:529
#, python-format
msgid ""
"There is a problem with your key pair.  Please verify that cert "
"%(cert_file)s and key %(key_file)s belong together.  OpenSSL error %(ce)s"
msgstr ""

#: glance/common/wsgi.py:49
msgid ""
"Address to bind the server.  Useful when selecting a particular network "
"interface."
msgstr ""

#: glance/common/wsgi.py:52
msgid "The port on which the server will listen."
msgstr ""

#: glance/common/wsgi.py:57
msgid "The backlog value that will be used when creating the TCP listener socket."
msgstr ""

#: glance/common/wsgi.py:60
msgid ""
"The value for the socket option TCP_KEEPIDLE.  This is the time in "
"seconds that the connection must be idle before TCP starts sending "
"keepalive probes."
msgstr ""

#: glance/common/wsgi.py:63
msgid "CA certificate file to use to verify connecting clients."
msgstr ""

#: glance/common/wsgi.py:65
msgid "Certificate file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:67
msgid "Private key file to use when starting API server securely."
msgstr ""

#: glance/common/wsgi.py:73
msgid ""
"The number of child process workers that will be created to service API "
"requests."
msgstr ""

#: glance/common/wsgi.py:76
msgid ""
"Name of eventlet hub to use. Traditionally, we have only supported "
"'poll', however 'selects' may be appropriate for some platforms. See "
"http://eventlet.net/doc/hubs.html for more details."
msgstr ""

#: glance/common/wsgi.py:81
msgid ""
"Maximum line size of message headers to be accepted. max_header_line may "
"need to be increased when using large tokens (typically those generated "
"by the Keystone v3 API with big service catalogs"
msgstr ""

#: glance/common/wsgi.py:127
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: glance/common/wsgi.py:165
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: glance/common/wsgi.py:240 glance/openstack/common/service.py:240
#, python-format
msgid "Starting %d workers"
msgstr ""

#: glance/common/wsgi.py:255
#, python-format
msgid "Removing dead child %s"
msgstr ""

#: glance/common/wsgi.py:258
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr ""

#: glance/common/wsgi.py:262
msgid "All workers have terminated. Exiting"
msgstr ""

#: glance/common/wsgi.py:270
msgid "Caught keyboard interrupt. Exiting."
msgstr ""

#: glance/common/wsgi.py:274
msgid "Exited"
msgstr ""

#: glance/common/wsgi.py:296
#, python-format
msgid "Child %d exiting normally"
msgstr ""

#: glance/common/wsgi.py:301
#, python-format
msgid "Started child %s"
msgstr ""

#: glance/common/wsgi.py:314
#, python-format
msgid "eventlet '%s' hub is not available on this platform"
msgstr ""

#: glance/common/wsgi.py:331
msgid "Starting single process server"
msgstr ""

#: glance/common/wsgi.py:537
msgid "Malformed JSON in request body."
msgstr ""

#: glance/common/location_strategy/__init__.py:25
msgid ""
"This value sets what strategy will be used to determine the image "
"location order. Currently two strategies are packaged with Glance "
"'location_order' and 'store_type'."
msgstr ""

#: glance/common/location_strategy/__init__.py:52
#, python-format
msgid ""
"%(strategy)s is registered as a module twice. %(module)s is not being "
"used."
msgstr ""

#: glance/common/location_strategy/__init__.py:61
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/location_strategy/__init__.py:74
#, python-format
msgid ""
"Invalid location_strategy option: %(name)s. The valid strategy option(s) "
"is(are): %(strategies)s"
msgstr ""

#: glance/common/location_strategy/store_type.py:26
msgid ""
"The store names to use to get store preference order. The name must be "
"registered by one of the stores defined by the 'known_stores' config "
"option. This option will be applied when you using 'store_type' option as"
" image location strategy defined by the 'location_strategy' config "
"option."
msgstr ""

#: glance/db/__init__.py:63 glance/db/__init__.py:164 glance/db/__init__.py:176
#: glance/db/sqlalchemy/api.py:159
#, python-format
msgid "No image found with ID %s"
msgstr ""

#: glance/db/__init__.py:235
#, python-format
msgid ""
"The target member %(member_id)s is already associated with image "
"%(image_id)s."
msgstr ""

#: glance/db/__init__.py:252
#, python-format
msgid "The specified member %s could not be found"
msgstr ""

#: glance/db/__init__.py:317 glance/db/__init__.py:342
#: glance/db/__init__.py:359 glance/db/simple/api.py:761
#, python-format
msgid "Could not find task %s"
msgstr ""

#: glance/db/simple/api.py:41
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr ""

#: glance/db/simple/api.py:46
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr ""

#: glance/db/simple/api.py:255 glance/db/sqlalchemy/api.py:385
msgid "Unable to filter on a range with a non-numeric value."
msgstr ""

#: glance/db/simple/api.py:328
#, python-format
msgid "Could not find image %s"
msgstr ""

#: glance/db/simple/api.py:332
msgid "Unable to get deleted image"
msgstr ""

#: glance/db/simple/api.py:336
msgid "Unable to get unowned image"
msgstr ""

#: glance/db/simple/api.py:424 glance/db/sqlalchemy/api.py:929
msgid "Image id is required."
msgstr ""

#: glance/db/simple/api.py:739 glance/db/simple/api.py:789
#: glance/db/sqlalchemy/api.py:1233
#, python-format
msgid "No task found with ID %s"
msgstr ""

#: glance/db/simple/api.py:766
#, python-format
msgid "Unable to get deleted task %s"
msgstr ""

#: glance/db/simple/api.py:771 glance/db/sqlalchemy/api.py:1239
#, python-format
msgid "Forbidding request, task %s is not visible"
msgstr ""

#: glance/db/simple/api.py:890
msgid "Task does not exist"
msgstr ""

#: glance/db/simple/api.py:912
#, python-format
msgid "No task info found with task id %s"
msgstr ""

#: glance/db/simple/api.py:928
#, python-format
msgid "Could not find task info %s"
msgstr ""

#: glance/db/sqlalchemy/api.py:58
msgid "Attempted to modify image user did not own."
msgstr ""

#: glance/db/sqlalchemy/api.py:59
msgid "You do not own this image"
msgstr ""

#: glance/db/sqlalchemy/api.py:165
#, python-format
msgid "Forbidding request, image %s not visible"
msgstr ""

#: glance/db/sqlalchemy/api.py:252
#: glance/openstack/common/db/sqlalchemy/utils.py:99
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: glance/db/sqlalchemy/api.py:315
#: glance/openstack/common/db/sqlalchemy/utils.py:121
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: glance/db/sqlalchemy/api.py:660
#: glance/tests/unit/v2/test_registry_client.py:484
#, python-format
msgid ""
"cannot transition from %(current)s to %(next)s in update (wanted "
"from_state=%(from)s)"
msgstr ""

#: glance/db/sqlalchemy/api.py:1062
#, python-format
msgid "TaskInfo was not found for task with id %(task_id)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:96
#, python-format
msgid "creating table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:102
#, python-format
msgid "dropping table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:82
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:145
msgid ""
"URI cannot contain more than one occurrence of a scheme.If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:89
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:152
#, python-format
msgid "Invalid store uri for image %(image_id)s: %(reason)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:121
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:184
#, python-format
msgid "Badly formed credentials '%(creds)s' in Swift URI"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:134
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:197
#: glance/store/swift.py:246
msgid "Badly formed credentials in Swift URI."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:152
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:215
#, python-format
msgid "Badly formed S3 URI: %(uri)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:66
msgid ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:87
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr ""

#: glance/domain/__init__.py:147
#, python-format
msgid "Property %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:150
#, python-format
msgid "Properties %s must be set prior to saving data."
msgstr ""

#: glance/domain/__init__.py:184
msgid "Attribute container_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:196
msgid "Attribute disk_format can be only replaced for a queued image."
msgstr ""

#: glance/domain/__init__.py:286
msgid "Status must be \"pending\", \"accepted\" or \"rejected\"."
msgstr ""

#: glance/domain/__init__.py:353
#, python-format
msgid "Task status changed from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/domain/__init__.py:358
#, python-format
msgid "Task status failed to change from %(cur_status)s to %(new_status)s"
msgstr ""

#: glance/image_cache/__init__.py:34
msgid "The driver to use for image cache management."
msgstr ""

#: glance/image_cache/__init__.py:36
msgid "The maximum size in bytes that the cache can use."
msgstr ""

#: glance/image_cache/__init__.py:38
msgid ""
"The amount of time to let an image remain in the cache without being "
"accessed"
msgstr ""

#: glance/image_cache/__init__.py:41
msgid "Base directory that the Image Cache uses."
msgstr ""

#: glance/image_cache/__init__.py:63
#, python-format
msgid "Image cache loaded driver '%s'."
msgstr ""

#: glance/image_cache/__init__.py:66
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""

#: glance/image_cache/__init__.py:73 glance/image_cache/__init__.py:92
msgid "Defaulting to SQLite driver."
msgstr ""

#: glance/image_cache/__init__.py:87
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""

#: glance/image_cache/__init__.py:174
msgid "Image cache has free space, skipping prune..."
msgstr ""

#: glance/image_cache/__init__.py:178
#, python-format
msgid ""
"Image cache currently %(overage)d bytes over max size. Starting prune to "
"max size of %(max_size)d "
msgstr ""

#: glance/image_cache/__init__.py:187
#, python-format
msgid "Pruning '%(image_id)s' to free %(size)d bytes"
msgstr ""

#: glance/image_cache/__init__.py:195
#, python-format
msgid ""
"Pruning finished pruning. Pruned %(total_files_pruned)d and "
"%(total_bytes_pruned)d."
msgstr ""

#: glance/image_cache/__init__.py:234
#, python-format
msgid "Tee'ing image '%s' into cache"
msgstr ""

#: glance/image_cache/__init__.py:253
#, python-format
msgid "Checksum verification failed. Aborted caching of image '%s'."
msgstr ""

#: glance/image_cache/__init__.py:263
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/prefetcher.py:46
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr ""

#: glance/image_cache/prefetcher.py:51
#, python-format
msgid "No metadata found for image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:56
#, python-format
msgid "Caching image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:68
msgid "Nothing to prefetch."
msgstr ""

#: glance/image_cache/prefetcher.py:72
#, python-format
msgid "Found %d images to prefetch"
msgstr ""

#: glance/image_cache/prefetcher.py:78
msgid "Failed to successfully cache all images in queue."
msgstr ""

#: glance/image_cache/prefetcher.py:82
#, python-format
msgid "Successfully cached all %d images"
msgstr ""

#: glance/image_cache/drivers/base.py:54
#, python-format
msgid "Failed to read %s from config"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:38
msgid ""
"The path to the sqlite file database that will be used for image cache "
"management."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:120
#, python-format
msgid "Failed to initialize the image cache database. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:159
#: glance/image_cache/drivers/xattr.py:143
msgid "Gathering cached image entries."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:298
#: glance/image_cache/drivers/xattr.py:271
#, python-format
msgid "Fetch finished, moving '%(incomplete_path)s' to '%(final_path)s'"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:322
#: glance/image_cache/drivers/xattr.py:287
#, python-format
msgid ""
"Fetch of cache file failed (%(e)s), rolling back by moving "
"'%(incomplete_path)s' to '%(invalid_path)s'"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:387
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:403
#: glance/image_cache/drivers/xattr.py:335
#, python-format
msgid "Not queueing image '%s'. Already cached."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:408
#: glance/image_cache/drivers/xattr.py:340
#, python-format
msgid "Not queueing image '%s'. Already being written to cache"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:414
#: glance/image_cache/drivers/xattr.py:346
#, python-format
msgid "Not queueing image '%s'. Already queued."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:432
#, python-format
msgid "Removed invalid cache file %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:446
#, python-format
msgid "Removed stalled cache file %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:448
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:482
#: glance/image_cache/drivers/xattr.py:436
#, python-format
msgid "Deleting image cache file '%s'"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:485
#: glance/image_cache/drivers/xattr.py:439
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr ""

#: glance/image_cache/drivers/xattr.py:103
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not"
" support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the "
"cache directory."
msgstr ""

#: glance/image_cache/drivers/xattr.py:279
#, python-format
msgid "Removing image '%s' from queue after caching it."
msgstr ""

#: glance/image_cache/drivers/xattr.py:351
#, python-format
msgid "Queueing image '%s'."
msgstr ""

#: glance/image_cache/drivers/xattr.py:381
#, python-format
msgid "No grace period, reaping '%(path)s' immediately"
msgstr ""

#: glance/image_cache/drivers/xattr.py:386
#, python-format
msgid "Cache entry '%(path)s' exceeds grace period, (%(age)i s > %(grace)i s)"
msgstr ""

#: glance/image_cache/drivers/xattr.py:392
#, python-format
msgid "Reaped %(reaped)s %(entry_type)s cache entries"
msgstr ""

#: glance/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: glance/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: glance/openstack/common/fileutils.py:63
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: glance/openstack/common/gettextutils.py:263
msgid "Message objects do not support addition."
msgstr ""

#: glance/openstack/common/gettextutils.py:272
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: glance/openstack/common/lockutils.py:103
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: glance/openstack/common/lockutils.py:168
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:177
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:187
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: glance/openstack/common/lockutils.py:205
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: glance/openstack/common/lockutils.py:209
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: glance/openstack/common/lockutils.py:247
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: glance/openstack/common/lockutils.py:251
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: glance/openstack/common/log.py:251
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: glance/openstack/common/log.py:352
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: glance/openstack/common/log.py:403
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: glance/openstack/common/log.py:573
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: glance/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: glance/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: glance/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: glance/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: glance/openstack/common/policy.py:395
#, python-format
msgid "Failed to understand rule %(rule)s"
msgstr ""

#: glance/openstack/common/policy.py:405
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: glance/openstack/common/policy.py:680
#, python-format
msgid "Failed to understand rule %(rule)r"
msgstr ""

#: glance/openstack/common/processutils.py:127
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: glance/openstack/common/processutils.py:142
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: glance/openstack/common/processutils.py:167
#: glance/openstack/common/processutils.py:240
#, python-format
msgid "Result was %s"
msgstr ""

#: glance/openstack/common/processutils.py:179
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: glance/openstack/common/processutils.py:219
#, python-format
msgid "Running cmd (SSH): %s"
msgstr ""

#: glance/openstack/common/processutils.py:221
msgid "Environment not supported over SSH"
msgstr ""

#: glance/openstack/common/processutils.py:225
msgid "process_input not supported over SSH"
msgstr ""

#: glance/openstack/common/service.py:112
#: glance/openstack/common/service.py:275
msgid "Full set of CONF:"
msgstr ""

#: glance/openstack/common/service.py:121
#: glance/openstack/common/service.py:218
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: glance/openstack/common/service.py:164
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: glance/openstack/common/service.py:200
msgid "Forking too fast, sleeping"
msgstr ""

#: glance/openstack/common/service.py:223
msgid "Unhandled exception"
msgstr ""

#: glance/openstack/common/service.py:230
#, python-format
msgid "Started child %d"
msgstr ""

#: glance/openstack/common/service.py:257
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: glance/openstack/common/service.py:261
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: glance/openstack/common/service.py:265
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: glance/openstack/common/service.py:293
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: glance/openstack/common/service.py:304
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: glance/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: glance/openstack/common/strutils.py:188
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: glance/openstack/common/strutils.py:195
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: glance/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:219
msgid "version should be an integer"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/migration.py:251
msgid "Upgrade DB using Essex release first."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:553
msgid "DB exception wrapped."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:621
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/session.py:703
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:196
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:202
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:282
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: glance/openstack/common/db/sqlalchemy/utils.py:303
msgid "Unsupported id columns type"
msgstr ""

#: glance/quota/__init__.py:307
#, python-format
msgid "Cleaning up %s after exceeding the quota."
msgstr ""

#: glance/registry/__init__.py:25
msgid "Address to find the registry server."
msgstr ""

#: glance/registry/__init__.py:27
msgid "Port the registry server is listening on."
msgstr ""

#: glance/registry/api/v1/images.py:105
#, python-format
msgid "Invalid marker. Image %(id)s could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:107 glance/registry/api/v1/images.py:112
msgid "Invalid marker. Image could not be found."
msgstr ""

#: glance/registry/api/v1/images.py:110 glance/registry/api/v1/images.py:325
#: glance/registry/api/v1/images.py:353 glance/registry/api/v1/images.py:466
#: glance/registry/api/v1/members.py:72 glance/registry/api/v1/members.py:106
#: glance/registry/api/v1/members.py:219 glance/registry/api/v1/members.py:279
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr ""

#: glance/registry/api/v1/images.py:144
msgid "Returning image list"
msgstr ""

#: glance/registry/api/v1/images.py:162
msgid "Returning detailed image list"
msgstr ""

#: glance/registry/api/v1/images.py:213
msgid "Unrecognized changes-since value"
msgstr ""

#: glance/registry/api/v1/images.py:218
msgid "protected must be True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:265
#, python-format
msgid "Unsupported sort_key. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:274
#, python-format
msgid "Unsupported sort_dir. Acceptable values: %s"
msgstr ""

#: glance/registry/api/v1/images.py:300
msgid "is_public must be None, True, or False"
msgstr ""

#: glance/registry/api/v1/images.py:316
#, python-format
msgid "Successfully retrieved image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:319 glance/registry/api/v1/images.py:357
#: glance/registry/api/v1/images.py:454 glance/registry/api/v1/members.py:66
#: glance/registry/api/v1/members.py:100 glance/registry/api/v1/members.py:213
#: glance/registry/api/v1/members.py:273
#, python-format
msgid "Image %(id)s not found"
msgstr ""

#: glance/registry/api/v1/images.py:343
#, python-format
msgid "Successfully deleted image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:347
#, python-format
msgid "Delete denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:383
#, python-format
msgid "Rejecting image creation request for invalid image id '%(bad_id)s'"
msgstr ""

#: glance/registry/api/v1/images.py:386
msgid "Invalid image id format"
msgstr ""

#: glance/registry/api/v1/images.py:396
#, python-format
msgid "Successfully created image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:400
#, python-format
msgid "Image with identifier %s already exists!"
msgstr ""

#: glance/registry/api/v1/images.py:404
#, python-format
msgid "Failed to add image metadata. Got error: %(e)s"
msgstr ""

#: glance/registry/api/v1/images.py:431
#, python-format
msgid "Updating image %(id)s with metadata: %(image_data)r"
msgstr ""

#: glance/registry/api/v1/images.py:445
#, python-format
msgid "Updating metadata for image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:460
#, python-format
msgid "Update denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:77
#, python-format
msgid "Returning member list for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:112 glance/registry/api/v1/members.py:225
#: glance/registry/api/v1/members.py:285
#, python-format
msgid "User lacks permission to share image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:114 glance/registry/api/v1/members.py:227
#: glance/registry/api/v1/members.py:287
msgid "No permission to share that image"
msgstr ""

#: glance/registry/api/v1/members.py:122 glance/registry/api/v1/members.py:138
#: glance/registry/api/v1/members.py:237
#, python-format
msgid "Invalid membership association specified for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:125 glance/registry/api/v1/members.py:141
#: glance/registry/api/v1/members.py:240
#, python-format
msgid "Invalid membership association: %s"
msgstr ""

#: glance/registry/api/v1/members.py:189
#, python-format
msgid "Successfully updated memberships for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:258
#, python-format
msgid "Successfully updated a membership for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:297
#, python-format
msgid "%(id)s is not a member of image %(image_id)s"
msgstr ""

#: glance/registry/api/v1/members.py:300 glance/registry/api/v1/members.py:317
msgid "Membership could not be found."
msgstr ""

#: glance/registry/api/v1/members.py:304
#, python-format
msgid "Successfully deleted a membership from image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:315
#, python-format
msgid "Member %(id)s not found"
msgstr ""

#: glance/registry/api/v1/members.py:320
#, python-format
msgid "Returning list of images shared with member %(id)s"
msgstr ""

#: glance/registry/api/v2/rpc.py:42
#, python-format
msgid "Registry service can't use %s"
msgstr ""

#: glance/registry/client/__init__.py:20
msgid ""
"The protocol to use for communication with the registry server.  Either "
"http or https."
msgstr ""

#: glance/registry/client/__init__.py:23
msgid "The path to the key file to use in SSL connections to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:26
msgid ""
"The path to the cert file to use in SSL connections to the registry "
"server."
msgstr ""

#: glance/registry/client/__init__.py:29
msgid ""
"The path to the certifying authority cert file to use in SSL connections "
"to the registry server."
msgstr ""

#: glance/registry/client/__init__.py:32
msgid ""
"When using SSL in connections to the registry server, do not require "
"validation via a certifying authority."
msgstr ""

#: glance/registry/client/__init__.py:36
msgid ""
"The period of time, in seconds, that the API server will wait for a "
"registry request to complete. A value of 0 implies no timeout."
msgstr ""

#: glance/registry/client/__init__.py:43
msgid ""
"Whether to pass through the user token when making requests to the "
"registry."
msgstr ""

#: glance/registry/client/__init__.py:46
msgid "The administrators user name."
msgstr ""

#: glance/registry/client/__init__.py:48
msgid "The administrators password."
msgstr ""

#: glance/registry/client/__init__.py:50
msgid "The tenant name of the administrative user."
msgstr ""

#: glance/registry/client/__init__.py:52
msgid "The URL to the keystone service."
msgstr ""

#: glance/registry/client/__init__.py:54
msgid "The strategy to use for authentication."
msgstr ""

#: glance/registry/client/__init__.py:56
msgid "The region for the authentication service."
msgstr ""

#: glance/registry/client/v1/api.py:33
msgid ""
"Whether to pass through headers containing user and tenant information "
"when making requests to the registry. This allows the registry to use the"
" context middleware without the keystoneclients' auth_token middleware, "
"removing calls to the keystone auth service. It is recommended that when "
"using this option, secure communication between glance api and glance "
"registry is ensured by means other than auth_token middleware."
msgstr ""

#: glance/registry/client/v1/api.py:78 glance/registry/client/v2/api.py:60
msgid "Configuration option was not valid"
msgstr ""

#: glance/registry/client/v1/api.py:82 glance/registry/client/v2/api.py:64
msgid "Could not find required configuration option"
msgstr ""

#: glance/registry/client/v1/api.py:159
msgid "Adding image metadata..."
msgstr ""

#: glance/registry/client/v1/api.py:166
#, python-format
msgid "Updating image metadata for image %s..."
msgstr ""

#: glance/registry/client/v1/api.py:173
#, python-format
msgid "Deleting image metadata for image %s..."
msgstr ""

#: glance/registry/client/v1/client.py:110
#, python-format
msgid ""
"Registry request %(method)s %(action)s HTTP %(status)s request id "
"%(request_id)s"
msgstr ""

#: glance/registry/client/v1/client.py:118
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr ""

#: glance/store/__init__.py:44
msgid ""
"List of which store classes and store class locations are currently known"
" to glance at startup."
msgstr ""

#: glance/store/__init__.py:47
msgid ""
"Default scheme to use to store image data. The scheme must be registered "
"by one of the stores defined by the 'known_stores' config option."
msgstr ""

#: glance/store/__init__.py:52 glance/store/scrubber.py:37
msgid ""
"Directory that the scrubber will use to track information about what to "
"delete. Make sure this is set in glance-api.conf and glance-scrubber.conf"
msgstr ""

#: glance/store/__init__.py:57
msgid "Turn on/off delayed delete."
msgstr ""

#: glance/store/__init__.py:59 glance/store/scrubber.py:42
msgid "The amount of time in seconds to delay before performing a delete."
msgstr ""

#: glance/store/__init__.py:181
#, python-format
msgid "%s Skipping store driver."
msgstr ""

#: glance/store/__init__.py:301
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/store/__init__.py:307
#, python-format
msgid "Failed to delete image %(image_id)s from store (%(error)s)"
msgstr ""

#: glance/store/__init__.py:340
#, python-format
msgid ""
"The image metadata key %(key)s has an invalid type of %(val)s.  Only "
"dict, list, and unicode are supported."
msgstr ""

#: glance/store/__init__.py:364
#, python-format
msgid ""
"The storage driver %(store)s returned invalid metadata %(metadata)s. This"
" must be a dictionary type"
msgstr ""

#: glance/store/__init__.py:373
#, python-format
msgid ""
"A bad metadata structure was returned from the %(store)s storage driver: "
"%(metadata)s.  %(error)s."
msgstr ""

#: glance/store/__init__.py:400
msgid "Skipping store.set_acls... not implemented."
msgstr ""

#: glance/store/__init__.py:450
#, python-format
msgid "Invalid location: %s"
msgstr ""

#: glance/store/__init__.py:639
#, python-format
msgid "Original locations is not empty: %s"
msgstr ""

#: glance/store/__init__.py:711
#, python-format
msgid "Get image %(id)s data from %(loc)s failed: %(err)s."
msgstr ""

#: glance/store/__init__.py:716
#, python-format
msgid "Glance tried all locations to get data for image %s but all have failed."
msgstr ""

#: glance/store/base.py:35 glance/tests/unit/test_store_base.py:51
#, python-format
msgid "Caught '%(exception)s' exception."
msgstr ""

#: glance/store/base.py:56
#, python-format
msgid "Failed to configure store correctly: %s Disabling add method."
msgstr ""

#: glance/store/cinder.py:88
#, python-format
msgid "Cinderclient connection created using URL: %s"
msgstr ""

#: glance/store/cinder.py:118
msgid "URI must start with cinder://"
msgstr ""

#: glance/store/cinder.py:126
#, python-format
msgid "URI contains invalid volume ID: %s"
msgstr ""

#: glance/store/cinder.py:149
msgid "Cinder storage requires a context."
msgstr ""

#: glance/store/cinder.py:153
msgid "Cinder storage requires a service catalog."
msgstr ""

#: glance/store/cinder.py:175
#, python-format
msgid "Failed to get image size due to volume can not be found: %s"
msgstr ""

#: glance/store/cinder.py:180
#, python-format
msgid "Failed to get image size due to internal error: %s"
msgstr ""

#: glance/store/filesystem.py:39
msgid "Directory to which the Filesystem backend store writes images."
msgstr ""

#: glance/store/filesystem.py:42
msgid ""
"The path to a file which contains the metadata to be returned with any "
"location associated with this store.  The file must contain a valid JSON "
"dict."
msgstr ""

#: glance/store/filesystem.py:73
#, python-format
msgid "No path specified in URI: %s"
msgstr ""

#: glance/store/filesystem.py:126
#, python-format
msgid "Could not find %s in configuration options."
msgstr ""

#: glance/store/filesystem.py:133
#, python-format
msgid "Directory to write image files does not exist (%s). Creating."
msgstr ""

#: glance/store/filesystem.py:144
#, python-format
msgid "Unable to create datadir: %s"
msgstr ""

#: glance/store/filesystem.py:154
#, python-format
msgid "Image file %s not found"
msgstr ""

#: glance/store/filesystem.py:169
#, python-format
msgid ""
"The JSON in the metadata file %(file)s could not be used: %(error)s  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:176
#, python-format
msgid ""
"The path for the metadata file %(file)s could not be opened: %(error)s  "
"An empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:183
#, python-format
msgid ""
"An error occurred processing the storage systems meta data file: %s.  An "
"empty dictionary will be returned to the client."
msgstr ""

#: glance/store/filesystem.py:199
#, python-format
msgid "Found image at %s. Returning in ChunkedFile."
msgstr ""

#: glance/store/filesystem.py:214
#, python-format
msgid "Found image at %s."
msgstr ""

#: glance/store/filesystem.py:233
#, python-format
msgid "Deleting image at %(fn)s"
msgstr ""

#: glance/store/filesystem.py:236
#, python-format
msgid "You cannot delete file %s"
msgstr ""

#: glance/store/filesystem.py:238
#, python-format
msgid "Image file %s does not exist"
msgstr ""

#: glance/store/filesystem.py:264
#, python-format
msgid "Image file %s already exists!"
msgstr ""

#: glance/store/filesystem.py:290
#, python-format
msgid ""
"Wrote %(bytes_written)d bytes to %(filepath)s with checksum "
"%(checksum_hex)s"
msgstr ""

#: glance/store/filesystem.py:302
#, python-format
msgid "Unable to remove partial image data for image %(id)s: %(error)s"
msgstr ""

#: glance/store/gridfs.py:97
msgid "Missing dependencies: pymongo"
msgstr ""

#: glance/store/gridfs.py:113 glance/store/s3.py:252 glance/store/swift.py:366
#: glance/store/vmware_datastore.py:219
#, python-format
msgid "Could not find %(param)s in configuration options."
msgstr ""

#: glance/store/gridfs.py:157
#, python-format
msgid "Could not find %s image in GridFS"
msgstr ""

#: glance/store/gridfs.py:180
#, python-format
msgid "GridFS already has an image at location %s"
msgstr ""

#: glance/store/gridfs.py:183
#, python-format
msgid "Adding a new image to GridFS with id %(id)s and size %(size)s"
msgstr ""

#: glance/store/gridfs.py:196
#, python-format
msgid "Uploaded image %(id)s, md5 %(md5)s, length %(length)s to GridFS"
msgstr ""

#: glance/store/http.py:80
#, python-format
msgid "Credentials '%s' not well-formatted."
msgstr ""

#: glance/store/http.py:87
msgid "No address specified in HTTP URL"
msgstr ""

#: glance/store/http.py:153
#, python-format
msgid "The HTTP URL exceeded %s maximum redirects."
msgstr ""

#: glance/store/http.py:165
#, python-format
msgid "HTTP URL returned a %s status code."
msgstr ""

#: glance/store/http.py:172
#, python-format
msgid "The HTTP URL attempted to redirect with an invalid %s status code."
msgstr ""

#: glance/store/rbd.py:51
msgid ""
"RADOS images will be chunked into objects of this size (in megabytes). "
"For best performance, this should be a power of two."
msgstr ""

#: glance/store/rbd.py:55
msgid "RADOS pool in which images are stored."
msgstr ""

#: glance/store/rbd.py:57
msgid ""
"RADOS user to authenticate as (only applicable if using Cephx. If <None>,"
" a default will be chosen based on the client. section in "
"rbd_store_ceph_conf)"
msgstr ""

#: glance/store/rbd.py:61
msgid ""
"Ceph configuration file path. If <None>, librados will locate the default"
" config. If using cephx authentication, this file should include a "
"reference to the right keyring in a client.<USER> section"
msgstr ""

#: glance/store/rbd.py:107
msgid "URI must start with rbd://"
msgstr ""

#: glance/store/rbd.py:108 glance/store/rbd.py:117 glance/store/rbd.py:130
#: glance/store/rbd.py:136
#, python-format
msgid "Invalid URI: %(uri)s: %(reason)s"
msgstr ""

#: glance/store/rbd.py:116
msgid "URI contains non-ascii characters"
msgstr ""

#: glance/store/rbd.py:129
msgid "URI must have exactly 1 or 4 components"
msgstr ""

#: glance/store/rbd.py:135
msgid "URI cannot contain empty components"
msgstr ""

#: glance/store/rbd.py:171 glance/store/rbd.py:235 glance/store/rbd.py:295
#, python-format
msgid "RBD image %s does not exist"
msgstr ""

#: glance/store/rbd.py:198 glance/store/sheepdog.py:197
#: glance/store/sheepdog.py:205
#, python-format
msgid "Error in store configuration: %s"
msgstr ""

#: glance/store/rbd.py:282
#, python-format
msgid "snapshot %(image)s@%(snap)s could not be unprotected because it is in use"
msgstr ""

#: glance/store/rbd.py:297
#, python-format
msgid "image %s could not be removed because it is in use"
msgstr ""

#: glance/store/rbd.py:328
msgid ""
"since image size is zero we will be doing resize-before-write for each "
"chunk which will be considerably slower than normal"
msgstr ""

#: glance/store/rbd.py:337
#, python-format
msgid "RBD image %s already exists"
msgstr ""

#: glance/store/rbd.py:353
#, python-format
msgid "resizing image to %s KiB"
msgstr ""

#: glance/store/rbd.py:356
#, python-format
msgid "writing chunk at offset %s"
msgstr ""

#: glance/store/s3.py:37
msgid "The host where the S3 server is listening."
msgstr ""

#: glance/store/s3.py:39
msgid "The S3 query token access key."
msgstr ""

#: glance/store/s3.py:41
msgid "The S3 query token secret key."
msgstr ""

#: glance/store/s3.py:43
msgid "The S3 bucket to be used to store the Glance data."
msgstr ""

#: glance/store/s3.py:45
msgid ""
"The local directory where uploads will be staged before they are "
"transferred into S3."
msgstr ""

#: glance/store/s3.py:48
msgid ""
"A boolean to determine if the S3 bucket should be created on upload if it"
" does not exist or if an error should be returned to the user."
msgstr ""

#: glance/store/s3.py:52
msgid ""
"The S3 calling format used to determine the bucket. Either subdomain or "
"path can be used."
msgstr ""

#: glance/store/s3.py:115
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"s3://accesskey:secretkey@https://s3.amazonaws.com/bucket/key-id, you need"
" to change it to use the s3+https:// scheme, like so: "
"s3+https://accesskey:secretkey@s3.amazonaws.com/bucket/key-id"
msgstr ""

#: glance/store/s3.py:123
#, python-format
msgid "Invalid store uri: %s"
msgstr ""

#: glance/store/s3.py:149
#, python-format
msgid "Badly formed S3 credentials %s"
msgstr ""

#: glance/store/s3.py:162
msgid "Badly formed S3 URI. Missing s3 service URL."
msgstr ""

#: glance/store/s3.py:165
#, python-format
msgid "Badly formed S3 URI: %s"
msgstr ""

#: glance/store/s3.py:307
#, python-format
msgid ""
"Retrieved image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""

#: glance/store/s3.py:367
#, python-format
msgid "S3 already has an image at location %s"
msgstr ""

#: glance/store/s3.py:371
#, python-format
msgid ""
"Adding image object to S3 using (s3_host=%(s3_host)s, "
"access_key=%(access_key)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""

#: glance/store/s3.py:393
#, python-format
msgid "Writing request body file to temporary file for %s"
msgstr ""

#: glance/store/s3.py:405
#, python-format
msgid "Uploading temporary file to S3 for %s"
msgstr ""

#: glance/store/s3.py:414
#, python-format
msgid ""
"Wrote %(size)d bytes to S3 key named %(obj_name)s with checksum "
"%(checksum_hex)s"
msgstr ""

#: glance/store/s3.py:442
#, python-format
msgid ""
"Deleting image object from S3 using (s3_host=%(s3_host)s, "
"access_key=%(accesskey)s, bucket=%(bucket)s, key=%(obj_name)s)"
msgstr ""

#: glance/store/s3.py:464
#, python-format
msgid "Could not find bucket with ID %s"
msgstr ""

#: glance/store/s3.py:505
#, python-format
msgid ""
"Failed to add bucket to S3.\n"
"Got error from S3: %(e)s"
msgstr ""

#: glance/store/s3.py:509
#, python-format
msgid ""
"The bucket %(bucket)s does not exist in S3. Please set the "
"s3_store_create_bucket_on_put option to add bucket to S3 automatically."
msgstr ""

#: glance/store/s3.py:528
#, python-format
msgid "Could not find key %(obj)s in bucket %(bucket)s"
msgstr ""

#: glance/store/scrubber.py:45
msgid ""
"A boolean that determines if the scrubber should clean up the files it "
"uses for taking data. Only one server in your deployment should be "
"designated the cleanup host."
msgstr ""

#: glance/store/scrubber.py:50
msgid ""
"Items must have a modified time that is older than this value in order to"
" be candidates for cleanup."
msgstr ""

#: glance/store/scrubber.py:133
#, python-format
msgid "%s file can not be read."
msgstr ""

#: glance/store/scrubber.py:157
#, python-format
msgid "%s file can not be wrote."
msgstr ""

#: glance/store/scrubber.py:208
#, python-format
msgid "%s directory does not exist."
msgstr ""

#: glance/store/scrubber.py:354
#, python-format
msgid "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"
msgstr ""

#: glance/store/scrubber.py:368
msgid "Daemon Shutdown on KeyboardInterrupt"
msgstr ""

#: glance/store/scrubber.py:372
msgid "Running application"
msgstr ""

#: glance/store/scrubber.py:375
#, python-format
msgid "Next run scheduled in %s seconds"
msgstr ""

#: glance/store/scrubber.py:380
#, python-format
msgid "Initializing scrubber with configuration: %s"
msgstr ""

#: glance/store/scrubber.py:404
#, python-format
msgid "Can not %s scrub jobs from queue."
msgstr ""

#: glance/store/scrubber.py:428
#, python-format
msgid "Scrubbing image %(id)s from %(count)d locations."
msgstr ""

#: glance/store/scrubber.py:443
#, python-format
msgid "Deleting URI from image %(image_id)s."
msgstr ""

#: glance/store/scrubber.py:456
#, python-format
msgid "Failed to delete URI from image %(image_id)s"
msgstr ""

#: glance/store/scrubber.py:468
#, python-format
msgid "%s file is not exists."
msgstr ""

#: glance/store/scrubber.py:473
#, python-format
msgid "%s file contains conflicting cleanup timestamp."
msgstr ""

#: glance/store/scrubber.py:492
#, python-format
msgid "%s file can not be created."
msgstr ""

#: glance/store/scrubber.py:506
#, python-format
msgid "Getting images deleted before %s"
msgstr ""

#: glance/store/sheepdog.py:42
msgid ""
"Images will be chunked into objects of this size (in megabytes). For best"
" performance, this should be a power of two."
msgstr ""

#: glance/store/sheepdog.py:46
msgid "Port of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:48
msgid "IP address of sheep daemon."
msgstr ""

#: glance/store/sheepdog.py:225 glance/store/sheepdog.py:244
#: glance/store/sheepdog.py:305
#, python-format
msgid "Sheepdog image %s does not exist"
msgstr ""

#: glance/store/sheepdog.py:266
#, python-format
msgid "Sheepdog image %s already exists"
msgstr ""

#: glance/store/swift.py:50
msgid "Whether to use ServiceNET to communicate with the Swift storage servers."
msgstr ""

#: glance/store/swift.py:53
msgid "The address where the Swift authentication service is listening."
msgstr ""

#: glance/store/swift.py:56
msgid "The user to authenticate against the Swift authentication service"
msgstr ""

#: glance/store/swift.py:59
msgid ""
"Auth key for the user authenticating against the Swift authentication "
"service."
msgstr ""

#: glance/store/swift.py:62
msgid ""
"Version of the authentication service to use. Valid versions are 2 for "
"keystone and 1 for swauth and rackspace"
msgstr ""

#: glance/store/swift.py:66
msgid ""
"If True, swiftclient won't check for a valid SSL certificate when "
"authenticating."
msgstr ""

#: glance/store/swift.py:69
msgid ""
"The region of the swift endpoint to be used for single tenant. This "
"setting is only necessary if the tenant has multiple swift endpoints."
msgstr ""

#: glance/store/swift.py:73
msgid ""
"A string giving the endpoint type of the swift service to use (publicURL,"
" adminURL or internalURL). This setting is only used if "
"swift_store_auth_version is 2."
msgstr ""

#: glance/store/swift.py:78
msgid ""
"A string giving the service type of the swift service to use. This "
"setting is only used if swift_store_auth_version is 2."
msgstr ""

#: glance/store/swift.py:83
msgid ""
"Container within the account that the account should use for storing "
"images in Swift."
msgstr ""

#: glance/store/swift.py:87
msgid ""
"The size, in MB, that Glance will start chunking image files and do a "
"large object manifest in Swift"
msgstr ""

#: glance/store/swift.py:91
msgid ""
"The amount of data written to a temporary disk buffer during the process "
"of chunking the image file."
msgstr ""

#: glance/store/swift.py:94
msgid ""
"A boolean value that determines if we create the container if it does not"
" exist."
msgstr ""

#: glance/store/swift.py:97
msgid ""
"If set to True, enables multi-tenant storage mode which causes Glance "
"images to be stored in tenant specific Swift accounts."
msgstr ""

#: glance/store/swift.py:101
msgid ""
"A list of tenants that will be granted read/write access on all Swift "
"containers created by Glance in multi-tenant mode."
msgstr ""

#: glance/store/swift.py:105
msgid ""
"If set to False, disables SSL layer compression of https swift requests. "
"Setting to False may improve performance for images which are already in "
"a compressed format, eg qcow2."
msgstr ""

#: glance/store/swift.py:110
msgid ""
"The number of times a Swift download will be retried before the request "
"fails."
msgstr ""

#: glance/store/swift.py:130
#, python-format
msgid "Swift exception raised %s"
msgstr ""

#: glance/store/swift.py:135
#, python-format
msgid "Stopping Swift retries after %d attempts"
msgstr ""

#: glance/store/swift.py:140
#, python-format
msgid ""
"Retrying Swift connection (%(retries)d/%(max_retries)d) with "
"range=%(start)d-%(end)d"
msgstr ""

#: glance/store/swift.py:214
msgid ""
"URI cannot contain more than one occurrence of a scheme. If you have "
"specified a URI like "
"swift://user:pass@http://authurl.com/v1/container/obj, you need to change"
" it to use the swift+http:// scheme, like so: "
"swift+http://user:pass@authurl.com/v1/container/obj"
msgstr ""

#: glance/store/swift.py:220
#, python-format
msgid "Invalid store URI: %(reason)s"
msgstr ""

#: glance/store/swift.py:264
msgid "Badly formed Swift URI."
msgstr ""

#: glance/store/swift.py:328
#, python-format
msgid "Swift could not find object %s."
msgstr ""

#: glance/store/swift.py:375
#, python-format
msgid "Deleting chunk %s"
msgstr ""

#: glance/store/swift.py:379
#, python-format
msgid "Failed to delete orphaned chunk %(container)s/%(chunk)s"
msgstr ""

#: glance/store/swift.py:391
#, python-format
msgid "Adding image object '%(obj_name)s' to Swift"
msgstr ""

#: glance/store/swift.py:411
msgid "Cannot determine image size. Adding as a segmented object to Swift."
msgstr ""

#: glance/store/swift.py:440
msgid "Error during chunked upload to backend, deleting stale chunks"
msgstr ""

#: glance/store/swift.py:447
#, python-format
msgid ""
"Wrote chunk %(chunk_name)s (%(chunk_id)d/%(total_chunks)s) of length "
"%(bytes_read)d to Swift returning MD5 of content: %(chunk_etag)s"
msgstr ""

#: glance/store/swift.py:461
msgid "Deleting final zero-length chunk"
msgstr ""

#: glance/store/swift.py:498
msgid "Swift already has an image at this location"
msgstr ""

#: glance/store/swift.py:500
#, python-format
msgid ""
"Failed to add object to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""

#: glance/store/swift.py:541 glance/store/swift.py:702
msgid "Swift could not find image at URI."
msgstr ""

#: glance/store/swift.py:562
#, python-format
msgid ""
"Failed to add container to Swift.\n"
"Got error from Swift: %(e)s"
msgstr ""

#: glance/store/swift.py:566
#, python-format
msgid ""
"The container %(container)s does not exist in Swift. Please set the "
"swift_store_create_container_on_put optionto add container to Swift "
"automatically."
msgstr ""

#: glance/store/swift.py:610
msgid "Location is missing user:password information."
msgstr ""

#: glance/store/swift.py:622
#, python-format
msgid "Badly formed tenant:user '%(user)s' in Swift URI"
msgstr ""

#: glance/store/swift.py:649
msgid "Multi-tenant Swift storage requires a context."
msgstr ""

#: glance/store/swift.py:653
msgid "Multi-tenant Swift storage requires a service catalog."
msgstr ""

#: glance/store/vmware_datastore.py:45
msgid ""
"ESX/ESXi or vCenter Server target system. The server value can be an IP "
"address or a DNS name."
msgstr ""

#: glance/store/vmware_datastore.py:48
msgid "Username for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:51
msgid "Password for authenticating with VMware ESX/VC server."
msgstr ""

#: glance/store/vmware_datastore.py:56
msgid ""
"Inventory path to a datacenter. If the vmware_server_host specified is an"
" ESX/ESXi, the vmware_datacenter_path is optional. If specified, it "
"should be \"ha-datacenter\"."
msgstr ""

#: glance/store/vmware_datastore.py:61
msgid "Datastore associated with the datacenter."
msgstr ""

#: glance/store/vmware_datastore.py:64
msgid ""
"Number of times VMware ESX/VC server API must be retried upon connection "
"related issues."
msgstr ""

#: glance/store/vmware_datastore.py:68
msgid ""
"The interval used for polling remote tasks invoked on VMware ESX/VC "
"server."
msgstr ""

#: glance/store/vmware_datastore.py:72
msgid ""
"The name of the directory where the glance images will be stored in the "
"VMware datastore."
msgstr ""

#: glance/store/vmware_datastore.py:76
msgid "Allow to perform insecure SSL requests to ESX/VC"
msgstr ""

#: glance/store/vmware_datastore.py:164
#, python-format
msgid "Badly formed VMware datastore URI %(uri)s."
msgstr ""

#: glance/store/vmware_datastore.py:205
#, python-format
msgid "Could not find datastore %(ds_name)s in datacenter %(dc_path)s"
msgstr ""

#: glance/store/vmware_datastore.py:259
#, python-format
msgid "Image file %(image_id)s already exists!"
msgstr ""

#: glance/store/vmware_datastore.py:327
#, python-format
msgid "The HTTP URL exceeded %(max_redirects)s maximum redirects."
msgstr ""

#: glance/store/vmware_datastore.py:336
msgid "VMware datastore could not find image at URI."
msgstr ""

#: glance/store/vmware_datastore.py:339
#, python-format
msgid "HTTP URL %(url)s returned a %(status)s status code."
msgstr ""

#: glance/store/vmware_datastore.py:346
#, python-format
msgid ""
"The HTTP URL %(path)s attempted to redirect with an invalid %(status)s "
"status code."
msgstr ""

#: glance/store/vmware/api.py:73
#, python-format
msgid "Failure while invoking function: %(func)s. Error: %(excep)s."
msgstr ""

#: glance/store/vmware/api.py:159
#, python-format
msgid "Error while terminating session: %s."
msgstr ""

#: glance/store/vmware/api.py:162
msgid "Successfully established connection to the server."
msgstr ""

#: glance/store/vmware/api.py:169
#, python-format
msgid "Error while logging out the user: %s."
msgstr ""

#: glance/store/vmware/api.py:215
#, python-format
msgid ""
"Not authenticated error occurred. Will create session and try API call "
"again: %s."
msgstr ""

#: glance/store/vmware/api.py:258
#, python-format
msgid "Task: %(task)s progress: %(prog)s."
msgstr ""

#: glance/store/vmware/api.py:262
#, python-format
msgid "Task %s status: success."
msgstr ""

#: glance/store/vmware/api.py:266 glance/store/vmware/api.py:271
#, python-format
msgid "Task: %(task)s failed with error: %(err)s."
msgstr ""

#: glance/store/vmware/vim.py:155
#, python-format
msgid "Error(s): %s occurred in the call to RetrievePropertiesEx."
msgstr ""

#: glance/store/vmware/vim.py:194
#, python-format
msgid "No such SOAP method %(attr)s. Detailed error: %(excep)s."
msgstr ""

#: glance/store/vmware/vim.py:203
#, python-format
msgid "httplib error in %(attr)s: %(excep)s."
msgstr ""

#: glance/store/vmware/vim.py:214
#, python-format
msgid "Socket error in %(attr)s: %(excep)s."
msgstr ""

#: glance/store/vmware/vim.py:223
#, python-format
msgid "Type error in %(attr)s: %(excep)s."
msgstr ""

#: glance/store/vmware/vim.py:230
#, python-format
msgid "Error in %(attr)s. Detailed error: %(excep)s."
msgstr ""

#: glance/tests/unit/test_migrations.py:843
#, python-format
msgid "location: %s data lost"
msgstr ""

#~ msgid ""
#~ msgstr ""

#~ msgid "Invalid syslog facility"
#~ msgstr ""

#~ msgid "Could not find bucket with ID %(bucket_id)s"
#~ msgstr ""

#~ msgid ""
#~ "Provided image size must match the "
#~ "stored image size. (provided size: "
#~ "%(ps)d, stored size: %(ss)d)ps"
#~ msgstr ""

#~ msgid "Incoming image size of %s was not convertible to an integer."
#~ msgstr ""

#~ msgid "Cleaning up %s after exceeding the quota %s"
#~ msgstr ""

#~ msgid ""
#~ "Image %s could not be found after"
#~ " upload.The image may have been "
#~ "deleted during the upload: %s Cleaning"
#~ " up the chunks uploaded"
#~ msgstr ""

#~ msgid "Unable to upload duplicate image data for image: %s"
#~ msgstr ""

#~ msgid "The incoming image is too large: %"
#~ msgstr ""

#~ msgid "Total size is %d bytes across %d images"
#~ msgstr ""

#~ msgid ""
#~ "Whether to include the backend image "
#~ "storage location in image properties. "
#~ "Revealing storage location can bea "
#~ "security risk, so use this setting "
#~ "with caution!"
#~ msgstr ""

#~ msgid "Missing required argument."
#~ msgstr ""

#~ msgid "'%(strategy)s' is not an available notifier strategy."
#~ msgstr ""

#~ msgid "Couldn't find property protection file %s:%s."
#~ msgstr ""

#~ msgid ""
#~ "Multiple policies '%s' not allowed for"
#~ " a given operation. Policies can be"
#~ " combined in the policy file"
#~ msgstr ""

#~ msgid "Encountered a malformed property protection rule %s:%s."
#~ msgstr ""

#~ msgid ""
#~ "Malformed property protection rule '%s': "
#~ "'@' and '!' are mutually exclusive"
#~ msgstr ""

#~ msgid "There is a problem with your %s %s.  Please verify it.  Error: %s"
#~ msgstr ""

#~ msgid ""
#~ "There is a problem with your %s"
#~ " %s.  Please verify it. OpenSSL "
#~ "error: %s"
#~ msgstr ""

#~ msgid ""
#~ "There is a problem with your key"
#~ " pair.  Please verify that cert %s"
#~ " and key %s belong together.  OpenSSL"
#~ " error %s"
#~ msgstr ""

#~ msgid "Could not bind to %s:%s after trying for 30 seconds"
#~ msgstr ""

#~ msgid ""
#~ "A valid SQLAlchemy connection string for"
#~ " the registry database. Default: "
#~ "%(default)s"
#~ msgstr ""

#~ msgid ""
#~ "Period in seconds after which SQLAlchemy"
#~ " should reestablish its connection to "
#~ "the database."
#~ msgstr ""

#~ msgid "The number of times to retry a connection to the SQLserver."
#~ msgstr ""

#~ msgid ""
#~ "The amount of time to wait (in "
#~ "seconds) before attempting to retry the"
#~ " SQL connection."
#~ msgstr ""

#~ msgid ""
#~ "A boolean that determines if the "
#~ "database will be automatically created."
#~ msgstr ""

#~ msgid "Enable debug logging in sqlalchemy which prints every query and result"
#~ msgstr ""

#~ msgid ""
#~ "Error configuring registry database with "
#~ "supplied sql_connection. Got error: %s"
#~ msgstr ""

#~ msgid "auto-creating glance registry DB"
#~ msgstr ""

#~ msgid "not auto-creating glance registry DB"
#~ msgstr ""

#~ msgid "SQL connection failed. %d attempts left."
#~ msgstr ""

#~ msgid "database is not under migration control"
#~ msgstr ""

#~ msgid "Upgrading database to version %s"
#~ msgstr ""

#~ msgid "Downgrading database to version %s"
#~ msgstr ""

#~ msgid "database is already under migration control"
#~ msgstr ""

#~ msgid "Invalid store uri for image %s: %s"
#~ msgstr ""

#~ msgid "Failed to decrypt location value for image %s"
#~ msgstr ""

#~ msgid ""
#~ "Exception encountered while tee'ing image "
#~ "'%s' into cache: %s. Continuing with "
#~ "response."
#~ msgstr ""

#~ msgid ""
#~ "Notifications can be sent when images"
#~ " are create, updated or deleted. "
#~ "There are three methods of sending "
#~ "notifications, logging (via the log_file "
#~ "directive), rabbit (via a rabbitmq "
#~ "queue), qpid (via a Qpid message "
#~ "queue), or noop (no notifications sent,"
#~ " the default)."
#~ msgstr ""

#~ msgid "Converted strategy alias %s to %s"
#~ msgstr ""

#~ msgid "No strategy alias found for %s"
#~ msgstr ""

#~ msgid "Cannot save data for image %s: %s"
#~ msgstr ""

#~ msgid "Unable to upload duplicate image data for image %s: %s"
#~ msgstr ""

#~ msgid "Not allowed to upload image data for image %s: %s"
#~ msgstr ""

#~ msgid ""
#~ "Image %s could not be found after"
#~ " upload. The image may have been "
#~ "deleted during the upload: %s"
#~ msgstr ""

#~ msgid "Failed to upload image data for image %s due to HTTP error: %s"
#~ msgstr ""

#~ msgid "Failed to upload image data for image %s due to internal error: %s"
#~ msgstr ""

#~ msgid "The host name of the rabbitmq server"
#~ msgstr ""

#~ msgid "The port on which the rabbitmq server is listening"
#~ msgstr ""

#~ msgid "A boolean value indicating if the selected rabbitmq server uses SSL."
#~ msgstr ""

#~ msgid "The user ID for authentication with rabbitmq."
#~ msgstr ""

#~ msgid ""
#~ "The password that will be used for"
#~ " authentication with the rabbitmq server."
#~ msgstr ""

#~ msgid "The virtual host used in the rabbitmq connection."
#~ msgstr ""

#~ msgid "Exchange name to use for connection when using rabbit strategy."
#~ msgstr ""

#~ msgid "Topic to use for connection when using rabbit strategy."
#~ msgstr ""

#~ msgid "The maximum number of times to attempt to connect to the AMQP server."
#~ msgstr ""

#~ msgid ""
#~ "This value multiplied by the number "
#~ "of connection attempts gives the amount"
#~ " of time in seconds to sleep "
#~ "between connection attempts to the AMQP"
#~ " server."
#~ msgstr ""

#~ msgid ""
#~ "The maximum amount of time to wait"
#~ " between connection attempts.  The delay"
#~ " time will be the smaller of "
#~ "this value and the value of "
#~ "<rabbit_retry_backoff> * <the number of "
#~ "failed connection attempts so far>."
#~ msgstr ""

#~ msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
#~ msgstr ""

#~ msgid "Connecting to AMQP server on %(hostname)s:%(port)d"
#~ msgstr ""

#~ msgid "Connected to AMQP server on %(hostname)s:%(port)d"
#~ msgstr ""

#~ msgid ""
#~ "Unable to connect to AMQP server "
#~ "on %(hostname)s:%(port)d after %(max_retries)d "
#~ "tries: %(err_str)s"
#~ msgstr ""

#~ msgid ""
#~ "AMQP server on %(hostname)s:%(port)d is "
#~ "unreachable: %(err_str)s. Trying again in "
#~ "%(sleep_time)d seconds."
#~ msgstr ""

#~ msgid "Notification with priority %(priority)s failed: msg=%(msg)s"
#~ msgstr ""

#~ msgid "Unable to send notification: %s"
#~ msgstr ""

#~ msgid "Connected to AMQP server on %s"
#~ msgstr ""

#~ msgid "Notification error.  Priority: %(priority)s Message: %(msg)s"
#~ msgstr ""

#~ msgid "Got mysql server has gone away: %s"
#~ msgstr ""

#~ msgid "%s not in valid priorities"
#~ msgstr ""

#~ msgid ""
#~ "Problem '%(e)s' attempting to send to"
#~ " notification system. Payload=%(payload)s"
#~ msgstr ""

#~ msgid "Failed to load notifier %s. These notifications will not be sent."
#~ msgstr ""

#~ msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
#~ msgstr ""

#~ msgid "Could not send notification to %(topic)s. Payload=%(message)s"
#~ msgstr ""

#~ msgid "The tenant name of the adminstrative user."
#~ msgstr ""

#~ msgid "Failed to delete image %s from store (%s)"
#~ msgstr ""

#~ msgid ""
#~ "The image metadata key %s has an"
#~ " invalid type of %s.  Only dict, "
#~ "list, and unicode are supported."
#~ msgstr ""

#~ msgid ""
#~ "The storage driver %s returned invalid"
#~ " metadata %sThis must be a dictionary"
#~ " type"
#~ msgstr ""

#~ msgid ""
#~ "A bad metadata structure was returned"
#~ " from the %s storage driver: %s.  "
#~ "%s."
#~ msgstr ""

#~ msgid ""
#~ "The JSON in the metadata file %s"
#~ " could not be used: %s  An "
#~ "empty dictionary will be returned to "
#~ "the client."
#~ msgstr ""

#~ msgid ""
#~ "The path for the metadata file %s"
#~ " could not be opened: %s  An "
#~ "empty dictionary will be returned to "
#~ "the client."
#~ msgstr ""

#~ msgid ""
#~ "An error occured processing the storage"
#~ " systems meta data file: %s.  An "
#~ "empty dictionary will be returned to "
#~ "the client."
#~ msgstr ""

#~ msgid "Unable to remove partial image data for image %s: %s"
#~ msgstr ""

#~ msgid "Missing dependecies: pymongo"
#~ msgstr ""

#~ msgid "Adding a new image to GridFS with id %s and size %s"
#~ msgstr ""

#~ msgid "Uploaded image %s, md5 %s, length %s to GridFS"
#~ msgstr ""

#~ msgid "The HTTP URL attempted to redirect with an invalid status code."
#~ msgstr ""

#~ msgid "RADOS user to authenticate as (only applicable if using cephx.)"
#~ msgstr ""

#~ msgid "Ceph configuration file path."
#~ msgstr ""

#~ msgid ""
#~ "The local directory where uploads will"
#~ " be staged before they are transfered"
#~ " into S3."
#~ msgstr ""

#~ msgid "Failed to delete orphaned chunk %s/%s"
#~ msgstr ""

