# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
#
# Translators:
# Maxime COQUEREL <max.coquerel@gmail.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Glance\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-20 06:02+0000\n"
"PO-Revision-Date: 2015-02-06 07:59+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: French (http://www.transifex.com/projects/p/glance/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: glance/location.py:403
#, python-format
msgid ""
"Glance tried all active locations to get data for image %s but all have "
"failed."
msgstr ""

#: glance/scrubber.py:168
#, python-format
msgid "%s file can not be read."
msgstr "Le fichier %s ne peut pas etre lu."

#: glance/scrubber.py:191
#, python-format
msgid "%s file can not be wrote."
msgstr "Le fichier %s ne peut pas etre écrit."

#: glance/scrubber.py:517
#, python-format
msgid "Can not %(op)s scrub jobs from queue: %(err)s"
msgstr ""

#: glance/scrubber.py:618
#, python-format
msgid "%s file can not be created."
msgstr "Le fichier %s ne peut pas etre créé"

#: glance/api/common.py:54
#, python-format
msgid ""
"An error occurred reading from backend storage for image %(image_id)s: "
"%(err)s"
msgstr ""
"Une erreur s'est produite pendant le stockage backend de l'image "
"%(image_id)s : %(err)s "

#: glance/api/common.py:60
#, python-format
msgid ""
"Backend storage for image %(image_id)s disconnected after writing only "
"%(bytes_written)d bytes"
msgstr ""
"Le stockage d'arrière plan pour l'image %(image_id)s s'est déconnecté après "
"l'écriture de seulement %(bytes_written)d octets "

#: glance/api/common.py:91
#, python-format
msgid "An error occurred during image.send notification: %(err)s"
msgstr "Une erreur s'est produite lors de la notification image.send : %(err)s"

#: glance/api/common.py:119
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr "Valeur invalide pour l'option user_storage_quota: %(users_quota)s"

#: glance/api/middleware/cache.py:169
#, python-format
msgid ""
"Image cache contained image file for image '%s', however the registry did "
"not contain metadata for that image!"
msgstr ""
"Le cache d'image contenait un fichier image pour l'image '%s', néanmoins le "
"registre ne contenait pas de métadonnées pour cette image ! "

#: glance/api/middleware/cache.py:268
#, python-format
msgid "could not find %s"
msgstr "impossible de trouver %s"

#: glance/api/middleware/cache.py:287
msgid "Checksum header is missing."
msgstr "L'en-tête de total de contrôle est manquant."

#: glance/api/v1/images.py:599
#, python-format
msgid "Copy from external source '%(scheme)s' failed for image: %(image)s"
msgstr ""
"Echec de copie depuis la source externe '%(scheme)s' pour l'image: %(image)s"

#: glance/api/v1/upload_utils.py:79
#, python-format
msgid "Unable to kill image %(id)s: "
msgstr "Impossible de supprimer l'image %(id)s :"

#: glance/api/v1/upload_utils.py:266
#, python-format
msgid "Received HTTP error while uploading image %s"
msgstr "Une erreur HTTP a été reçu lors du chargement de l'image %s"

#: glance/api/v2/image_data.py:60
#, python-format
msgid "Unable to restore image %(image_id)s: %(e)s"
msgstr "Impossible de restaurer l'image %(image_id)s: %(e)s"

#: glance/api/v2/image_data.py:155 glance/api/v2/image_data.py:159
msgid "Failed to upload image data due to HTTP error"
msgstr ""
"Echec de téléchargement des données de l'image en raison d'une erreur HTTP"

#: glance/api/v2/image_data.py:164
msgid "Failed to upload image data due to internal error"
msgstr ""
"Echec de téléchargement des données de l'image en raison d'une erreur interne"

#: glance/api/v2/metadef_namespaces.py:205
#, python-format
msgid "Failed to delete namespace %(namespace)s "
msgstr "Echec lors de la suppresion du namespace %(namespace)s"

#: glance/async/__init__.py:67
msgid ""
"This execution of Tasks is not setup. Please consult the project "
"documentation for more information on the executors available."
msgstr ""

#: glance/async/__init__.py:71
msgid "Internal error occurred while trying to process task."
msgstr "Erreur interne s'est produite lors du traitement de la tâche ."

#: glance/async/taskflow_executor.py:101
#, python-format
msgid "Failed to execute task %(task_id)s: %(exc)s"
msgstr ""

#: glance/common/property_utils.py:103
#, python-format
msgid ""
"Multiple policies '%s' not allowed for a given operation. Policies can be "
"combined in the policy file"
msgstr ""

#: glance/common/store_utils.py:71
#, python-format
msgid "Failed to delete image %(image_id)s from store: %(exc)s"
msgstr "Echec de supprésion de l'image %(image_id)s depuis le magasin: %(exc)s"

#: glance/common/swift_store_utils.py:101
msgid "Invalid format of swift store config cfg"
msgstr ""

#: glance/common/wsgi.py:288
#, python-format
msgid "Not respawning child %d, cannot recover from termination"
msgstr "Aucune relance de l'enfant %d, récupération impossible après arrêt"

#: glance/common/location_strategy/__init__.py:65
#, python-format
msgid "Failed to load location strategy module %(module)s: %(e)s"
msgstr ""

#: glance/common/scripts/__init__.py:40
#, python-format
msgid ""
"This task type %(task_type)s is not supported by the current deployment of "
"Glance. Please refer the documentation provided by OpenStack or your "
"operator for more information."
msgstr ""

#: glance/common/scripts/__init__.py:50
#, python-format
msgid "Failed to save task %(task_id)s in DB as task_repo is %(task_repo)s"
msgstr ""

#: glance/common/scripts/utils.py:47
#, python-format
msgid "Task not found for task_id %s"
msgstr "Tache non trouvé pour  task_id %s"

#: glance/db/sqlalchemy/metadata.py:142
#, python-format
msgid "Json schema files not found in %s. Aborting."
msgstr "Fichier du schéma Json non trouvé dans %s. Abandon."

#: glance/db/sqlalchemy/migrate_repo/versions/015_quote_swift_credentials.py:63
#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:97
#, python-format
msgid "Invalid store uri for image: %(image_id)s. Details: %(reason)s"
msgstr "uri magasin non valide pour image: %(image_id)s. Details: %(reason)s"

#: glance/domain/__init__.py:474
#, python-format
msgid "Failed to load the %s executor provided in the config."
msgstr ""

#: glance/image_cache/__init__.py:271
#, python-format
msgid ""
"Exception encountered while tee'ing image '%(image_id)s' into cache: "
"%(error)s. Continuing with response."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:398
#, python-format
msgid "Error executing SQLite call. Got error: %s"
msgstr "Erreur lors de l'exécution de l'appel SQLite. Erreur obtenue : %s"

#: glance/image_cache/drivers/xattr.py:109
#, python-format
msgid ""
"The device housing the image cache directory %(image_cache_dir)s does not "
"support xattr. It is likely you need to edit your fstab and add the "
"user_xattr option to the appropriate line for the device housing the cache "
"directory."
msgstr ""
"L'unité hébergeant le répertoire de cache d'image %(image_cache_dir)s ne "
"prend pas en charge xattr. Vous devez probablement éditer votre fstab et "
"ajouter l'option user_xattr sur la ligne appropriée de l'unité hébergeant le "
"répertoire de cache."

#: glance/openstack/common/policy.py:550 glance/openstack/common/policy.py:830
#, python-format
msgid "Failed to understand rule %s"
msgstr "Échec de compréhension de la règle %s"

#: glance/openstack/common/policy.py:560
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Aucun gestionnaire pour ce type de correspondance %s"

#: glance/registry/api/v1/images.py:136
msgid "Unable to get images"
msgstr "Impossible d'obtenir les images."

#: glance/registry/api/v1/images.py:354
#, python-format
msgid "Unable to show image %s"
msgstr "Impossible d'afficher l'image %s"

#: glance/registry/api/v1/images.py:390
#, python-format
msgid "Unable to delete image %s"
msgstr "Impossible de supprimer l'image %s"

#: glance/registry/api/v1/images.py:442
#, python-format
msgid "Unable to create image %s"
msgstr "Impossible de créer l'image %s"

#: glance/registry/api/v1/images.py:515
#, python-format
msgid "Unable to update image %s"
msgstr "Impossible de mettre à jour l'image %s"

#: glance/registry/client/v1/client.py:129
#, python-format
msgid "Registry client request %(method)s %(action)s raised %(exc_name)s"
msgstr "Demande client de registre %(method)s %(action)s produite %(exc_name)s"

#: glance/tests/functional/v2/test_metadef_resourcetypes.py:99
#, python-format
msgid "Forbidden to create resource type. Reason: %(reason)s"
msgstr "Creation du type de ressource refuse. Raison: %(reason)s "
