# Translations template for glance.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2014.2.dev41.gd8d15d3\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-08-20 06:06+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/scrubber.py:197
#, python-format
msgid "Failed to find image to delete: %s"
msgstr ""

#: glance/scrubber.py:540
#, python-format
msgid "Unable to delete URI from image %s."
msgstr ""

#: glance/api/common.py:116
#, python-format
msgid "Invalid value for option user_storage_quota: %(users_quota)s"
msgstr ""

#: glance/api/v2/images.py:822
#, python-format
msgid ""
"Could not find schema properties file %s. Continuing without custom "
"properties"
msgstr ""

#: glance/cmd/manage.py:88
msgid ""
"Warning: The db_enforce_mysql_charset option is now deprecated and will "
"be removed in the Juno release. Please migrate DB manually e.g. convert "
"data of all tables to UTF-8 charset."
msgstr ""

#: glance/common/store_utils.py:63
#, python-format
msgid "Failed to delete image %s in store from URI"
msgstr ""

#: glance/db/sqlalchemy/api.py:65
msgid "Deadlock detected. Retrying..."
msgstr ""

#: glance/db/sqlalchemy/api.py:313
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:90
#, python-format
msgid "Failed to decrypt location value for image %(image_id)s"
msgstr ""

#: glance/image_cache/__init__.py:71
#, python-format
msgid ""
"Image cache driver '%(driver_name)s' failed to load. Got error: "
"'%(import_err)s."
msgstr ""

#: glance/image_cache/__init__.py:92
#, python-format
msgid ""
"Image cache driver '%(driver_module)s' failed to configure. Got error: "
"'%(config_err)s"
msgstr ""

#: glance/image_cache/prefetcher.py:48
#, python-format
msgid "Image '%s' is not active. Not caching."
msgstr ""

#: glance/image_cache/prefetcher.py:53
#, python-format
msgid "No metadata found for image '%s'"
msgstr ""

#: glance/image_cache/prefetcher.py:80
msgid "Failed to successfully cache all images in queue."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:458
#, python-format
msgid "Failed to delete file %(path)s. Got error: %(e)s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:495
#: glance/image_cache/drivers/xattr.py:446
#, python-format
msgid "Cached image file '%s' doesn't exist, unable to delete"
msgstr ""

#: glance/openstack/common/network_utils.py:146
msgid "tcp_keepidle not available on your system"
msgstr ""

#: glance/openstack/common/network_utils.py:153
msgid "tcp_keepintvl not available on your system"
msgstr ""

#: glance/openstack/common/network_utils.py:160
msgid "tcp_keepknt not available on your system"
msgstr ""

